Create new task in form 2
taniryuu/Rer_Pro pull request #101
Opened 2020-11-10 15:03 UTC by ruffini47

## やったこと
進捗が完了済以外で「未」のタスクが無いとき、ユーザがタスク名、完了予定日を指定して「未」のタスクを新規作成できるようにした。
## やらないこと
「未」のタスク作成フォームに入力しても反映されない場合、「未」のタスク作成フォームを表示しないようにすること。
## できるようになること(ユーザ目線)
「未」のタスク作成するとき、タスク名、完了予定日をユーザーが指定できるようになる。
## できなくなること(ユーザ目線)
「未」のタスク作成するとき、タスク名、完了予定日を指定しない自動「未」タスク生成。
## 動作確認
TaskのCRUD操作、StepのCRUD操作全般、
## その他
親子モデル同時フォーム更新を使うと不具合を生じるので使わず、単なるfields_forを使って実装しました。

2020-11-10 15:16 UTC, ruffini47 commented
今まで、自動でタスク名を"new_task"、完了予定日を本日にしていたところをユーザーが指定できるようにしました。新規進捗作成時、進捗直接編集時などでフォームを表示して入力できるようにしました。
その際、親子モデル同時フォーム更新は使わず、単なるfields_forを使いました。
レビューをお願い致します。

2020-11-11 03:57 UTC, fumihisasuzuki requested changes
時間の関係でまだ半分しか見れていませんが、取り急ぎコメント致します。

2020-11-11 03:57 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +      end
このメソッドの中で、`@step`は使用していません。
引数としてとってきている`step`を使用していますので、そちらに合わせる方が今後のバグが少なくなると思います。
もしあえて`@step`を使用しているようでしたら、理由を教えていただけると幸いです。

2020-11-11 03:57 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +    if params[:completed_id].present? && lead.errors.blank? && step.errors.blank? && (@task.present? && @task.errors.blank?)
毎度、@taskの存在確認をしてからエラーがあるかチェックするのは、あまりDRYでないですよね・・・リファクタリング出来る気がします。

例えば、このメソッドの最初（17行目）に、
`task = step.tasks.new`
などと定義しておくのはいかがでしょうか？
そうすれば、存在確認が要らなくなりそうです。

ちなみに、最初にトランザクションの外で定義しておけば、インスタンス変数（`@task`）でなくてもメソッド内で`task`を使用できたはずです。

2020-11-11 03:57 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +    end
259行目は実装中のメモ書きの消し忘れでしょうか？（あえて残しているのであればそのままで良いです。）

2020-11-11 03:57 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
>        end
56～62行目と、64～69行目は全く同じことが書いてありますか？
でしたら、if構造の外に出してDRYにしませんか？

また、これでしたら三項演算子を使って書く方がシンプルと思います。

2020-11-11 10:30 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +    end
259行目は実装中の消し忘れです。消去しておきます。

2020-11-11 10:48 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
>        end
確かにif構造の外に出せば1回で済みますね。外に出して三項演算子で書き直しました。
なお、ここの本題とは違いますが、ここと関連したことなのですが、鈴木（文）さんの次のプルリクで良いので、新規で進捗を作成するとき、完了済み進捗を作成できるようになっているのですが、新規で完了済みの進捗を生成することがそもそもどうかなと思うので、新規で進捗を作成するときはステータスの選択ボックスの候補から完了済みは選べないようにしていただけないでしょうか？そうして頂けると、53行目から56行目までの「完了」のタスクを生成するコードは必要なくなるのですが。

2020-11-11 10:56 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      end
stepと書くべきところを誤って@stepと書いてしまっています。
ご指摘ありがとうございます。

2020-11-11 11:23 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +    if params[:completed_id].present? && lead.errors.blank? && step.errors.blank? && (@task.present? && @task.errors.blank?)
トランザクションの外でtaskを定義した場合、taskのフォームでタスク名や完了予定日を入力しなかった場合、バリデーションが上手く効かずに、新規進捗をタスク無しで作成してしまいますので、taskの定義はやはりトランザクションの中でしないといけなさそうです。

2020-11-11 11:47 UTC, taniryuu reviewed
確認遅れてすみません。
一件だけコメントしました。
ご教授お願いします。

2020-11-11 11:47 UTC, taniryuu commented on app/models/task.rb
> +  belongs_to :step, inverse_of: :tasks
このinverse_ofは初めて見ました。
自分でググってどんな役割なのかなど良い勉強になりました。
この設定はhas_manyで使ってる物が多いですがbelongs_toでも意味があるのですか？

https://qiita.com/akicho8/items/86417f955758b0715af2

2020-11-11 12:21 UTC, ruffini47 commented on app/models/task.rb
> +  belongs_to :step, inverse_of: :tasks
ここのinverse_ofは親子モデル同時フォーム更新をやっていた時に付けたもので、自分でも親子モデル同時フォーム更新が上手くいかいときのもので、自分でもよくわかっていないです。今は親子モデル同時フォーム更新をやっていないので消去しておいた方が良いかもしれません。

2020-11-12 01:22 UTC, taniryuu commented on app/models/task.rb
> +  belongs_to :step, inverse_of: :tasks
消去してうまく動けば良いですが、不具合出るようでしたら残しても良いですよ。
私も使ったことないので詳しくはわかりませんので。

2020-11-12 11:03 UTC, ruffini47 commented on app/models/task.rb
> +  belongs_to :step, inverse_of: :tasks
消去してテストしてみたのですが、大丈夫そうでしたので消去しておきます。

2020-11-13 03:31 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
>        end
ありがとうございます。「完了済の進捗」を作成できることの是非について、次回ミーティングで話せたらと思います。

2020-11-13 03:50 UTC, fumihisasuzuki commented
残りも見ましたが、残りは特にコメントありませんでした。
修正をお待ちしております。

2020-11-13 12:59 UTC, ruffini47 commented
谷口さん、鈴木(文)さんのコメントに対する修正をし、pushしました。
ご確認よろしくお願いいたします。

2020-11-13 15:17 UTC, taniryuu reviewed
すみません
追加で質問が出てきましたので返答お待ちしております。

2020-11-14 05:04 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    @task = Task.new
例えば、「完了済み」のstepを「進捗中」のstepに直接編集とします。「完了済み」stepには「未」のタスクが無く、「進捗中」のstepには「未」のタスクが必要なので、新規生成する「未」のタスクを@task = Task.newで指定しています。

2020-11-14 05:26 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    @task = Task.new(task_params)
上のeditのコメントで書いた理由で新規タスクを生成したいのですが、新規タスクを生成するときのタスク名、完了予定日の情報などをtask_paramsで持たせておくことで、バリデーションエラーがあったときにバリデーションとして引っ掛かるようにしています。@step.tasks.new(task_params)にしてしまうと即座にタスクを生成してしまって、@stepにタスクが無い場合にだけタスクを生成することに反してしまうので、@task=Task.new(task_params)としてから、update_and_errors_ofメソッドの中で、@task =Task.create(task_params)とすることでタスクを生成しています。

2020-11-14 13:19 UTC, taniryuu commented
ありがとうございます。Stepのステータスによって@taskを使用するイメージですね

2020-11-14 13:20 UTC, taniryuu approved these changes

2020-11-15 11:02 UTC, merged