案件のテンプレート一覧からコピー
taniryuu/Rer_Pro pull request #105
Opened 2020-11-19 14:09 UTC by fumihisasuzuki

## やったこと
* 案件のテンプレート一覧からテンプレートを選び、それに紐づく進捗及びタスクを丸々コピーできるようにした。
![image](https://user-images.githubusercontent.com/56940903/99676647-205b3a80-2abc-11eb-9483-bbde3d381f1c.png)

## やらないこと
* テンプレートの概念が出てきたことによるバリデーションの追加やバグ修正
* 進捗のみテンプレートから追加
## できるようになること(ユーザ目線)
* 案件のテンプレート一覧の表示
* 案件のテンプレート一覧からコピー
## できなくなること(ユーザ目線)
* なし
## 動作確認
* テンプレート一覧の表示、テンプレート一覧から、案件をコピーして編集できることを確認した。
## その他
* 案件一覧を使い回そうとパーシャル化しましたが、結局テンプレートの方でうまくDRYにすることができませんでした。これはこれでフォルダ構成は良くなったと思うので、そのままにしています。

2020-11-20 02:04 UTC, taniryuu requested changes
テンプレート一覧の詳細を開こうとするとエラーが出ますがここの修正は別のプルリクでしますか？

もう一点
今テンプレートを使うボタン&leads#create⇨leads#edit⇨名前を編集してleads#update
という流れですが
テンプレートを使うボタンで案件作成するよりleads/leads#newのフォームにテンプレートに格納されてた値を入れる方が自然な流れに感じるのですがどうですか？
というのも、テンプレートから作成時ミスがあった場合に新規作成時通知が出る仕様よりは保存されて通知が出る方が余計な通知がでないと思います。
↓こんな感じです
テンプレートを使うボタン⇨leads#new⇨編集してleads#create
フォームにvalue属性つけて作れると思います。

2020-11-20 09:51 UTC, fumihisasuzuki commented
詳細のエラーに関してはissueにあげております。
noticeがらみのエラーのようなんですが、、、

テンプレートからコピーの仕様について詰まっていなかったところかと思います。
明日か明後日ミーティングいかがでしょうか？

2020-11-20 14:41 UTC, ruffini47 commented on app/controllers/leads/template_controller.rb
> +  }, only: %i(index)
ここのbefore_actionの`->`表記はなんでしょうか？set_laedsはどこで定義されていますか？@leadsを定義しているのでしょうか？

2020-11-20 14:45 UTC, ruffini47 commented on app/controllers/leads/template_controller.rb
> +        status: "in_progress",
new_stepのstatusは、必ず進捗中としてコピーするのですか？他のステータスはコピーできないのでしょうか？

2020-11-20 14:53 UTC, ruffini47 commented on app/views/leads/index/_main.html.erb
> +    <%= form_with url: leads_path, method: :get, local: true do |f| %>
今更ですが、ここの表記をすると検索結果をリセットされますか？

2020-11-20 14:55 UTC, ruffini47 commented on app/views/leads/index/_main.html.erb
> +    <% end %>
今更ですが、ここの表記をすると検索結果がリセットされますか？

2020-11-20 15:16 UTC, ruffini47 commented on app/views/leads/leads/index.html.erb
>  <p id="notice"><%= notice %></p>
今更ですが、noticeの変数の内容はどこで定義されているものですか？

2020-11-20 15:25 UTC, ruffini47 commented
確認しました。
大筋の流れは理解できました。
何点か質問させて頂きました。

2020-11-21 07:19 UTC, fumihisasuzuki commented on app/controllers/leads/template_controller.rb
> +      room_num:	"#{@lead.room_num}(#{@lead.template_name}のコピー)",
確認しましたが、私のローカルでは半角が入っていました・・・

2020-11-21 07:19 UTC, fumihisasuzuki commented on app/controllers/leads/template_controller.rb
> +    redirect_to edit_lead_path(new_lead)
ありがとうございます、修正しました。

2020-11-21 07:20 UTC, fumihisasuzuki commented on app/views/leads/template/index.html.erb
> +<p id="notice"><%= notice %></p>
そうですね、消します。
フラッシュメッセージは別プルリクで調整させてください。他にもnoticeのままでいいのか？というところがあったような気がしたので。

2020-11-21 07:23 UTC, fumihisasuzuki commented on app/controllers/leads/template_controller.rb
> +  }, only: %i(index)
before_actionで引数を指定する場合は、このアロー関数の書き方をするようです。
http://ohs30359.hatenablog.com/entry/2016/08/13/130624

2020-11-21 07:24 UTC, fumihisasuzuki commented on app/controllers/leads/template_controller.rb
> +        status: "in_progress",
はい、そのつもりでした。

2020-11-21 07:24 UTC, fumihisasuzuki commented on app/views/leads/index/_main.html.erb
> +    <% end %>
このボタンを押すと、検索結果がリセットされて、全件表示されます。

2020-11-21 07:26 UTC, fumihisasuzuki commented on app/views/leads/leads/index.html.erb
>  <p id="notice"><%= notice %></p>
これは、schafoldでgenerateしたときに自動生成されたものなんですよね・・・
コントローラーで定義されているはずです。
最終的には、全てフラッシュメッセージに変換していきたいと思っています。

2020-11-21 07:26 UTC, fumihisasuzuki commented
本日のミーティングの内容を織り込んで修正致しますので、少々お待ちください。

2020-11-21 13:29 UTC, ruffini47 commented on app/views/leads/leads/index.html.erb
>  <p id="notice"><%= notice %></p>
flashメッセージを表示している部分ですね

2020-11-21 13:29 UTC, ruffini47 commented on app/views/leads/index/_main.html.erb
> +    <% end %>
なぜこれがリセットになるのかが、よくわからないのですが・・・

2020-11-21 13:30 UTC, ruffini47 commented on app/controllers/leads/template_controller.rb
> +  }, only: %i(index)
良く理解できました。
ありがとうございます。

2020-11-22 00:37 UTC, fumihisasuzuki commented
昨日のミーティングの内容を織り込んで修正致しました。
案件の新規作成ページに飛び、案件の作成に成功したときに初めて、紐づく進捗とタスクをテンプレートからコピーするように変更しました。
意外と、アクションもひとつ要らなくなりましたし、フォームもあまりいじらずに済んだと思うので、ご提案いただいて良かったです。
改めて、レビューをお願い致します。

2020-11-22 02:21 UTC, taniryuu approved these changes
確認しました！
コード量も減って自然な流れでテンプレートから保存できるようになってよかったです。
私からはマージして大丈夫です！

2020-11-22 11:41 UTC, ruffini47 approved these changes

2020-11-22 11:43 UTC, ruffini47 commented
修正の結果を確認しました。
大筋の流れを理解しました。
私からもOKなので、マージします。

2020-11-22 11:44 UTC, merged

2020-11-23 00:05 UTC, fumihisasuzuki commented on app/views/leads/index/_main.html.erb
> +    <% end %>
検索のシステムはご存知と思います。
form_withで、検索ワードをユーザーに入力してもらい、そのワードをsubmitすることで、コントローラー側で検索をかけています。

この5～7行目では、一切、検索ワードを入力する欄がなく、endで閉じております。つまり、検索ワードを全て""で送ることができますので、コントローラ側で絞り込みが行われず、全件表示になる、という流れです。

2020-11-23 16:08 UTC, ruffini47 commented on app/views/leads/index/_main.html.erb
> +    <% end %>
説明をして頂いてわかりました。
ありがとうございます。