Infinite loop of events after task operation
taniryuu/Rer_Pro pull request #107
Opened 2020-11-21 04:52 UTC by ruffini47

## やったこと
タスク操作後のイベントページで完了予定日などを空白にしてもエラーにならないようにしました。具体的には、
①タスク操作後のイベントページで新規タスク生成欄を空白にしたらそのページに留まり続ける。
②完了ボタン押下後のapp/views/stes_statuses/_indexページで新規タスク欄を空白にしたら、タスク操作後のイベントページにリダイレクトする。
③進捗新規作成時イベントページで進捗を削除するとき、それが唯一の進捗中進捗のときバリデーションで削除できないが、新規タスク生成フォームを使って新規タスク生成して終了するようにした。
## やらないこと
無し。
## できるようになること(ユーザ目線)
タスク操作後のイベントページでフォームを空白にしてもエラー状態にならないようにした。
## できなくなること(ユーザ目線)
*無し。
## 動作確認
TaskのCRUD操作、StepのCRUD操作、タスク操作後のイベントページ経由のリダイレクト確認。
## その他
* 具体的には新規タスク生成欄を空白にしたらそのページに留まり続けるようにroop_ok編集を導入しました。

2020-11-21 04:54 UTC, ruffini47 commented
タスク操作後のイベントページでフォームを空白にした時のエラーハンドリングしました。
レビューをよろしくお願いします。

2020-11-21 07:04 UTC, fumihisasuzuki requested changes
これは、roopした場合に、エラーメッセージは表示されますか？
完了予定日などを空白にした際は、本来、エラーメッセージと共にrenderで戻って来れるのがベターと思いますが、それは難しかったでしょうか？

あと、step_status#destroyの役割について補足していただけると幸いです。
パーシャルもイマイチコードを読んだだけでは理解できませんでした・・・

2020-11-21 07:04 UTC, fumihisasuzuki commented on app/views/leads/tasks/edit_continue_or_destroy_step.html.erb
> +
`@step.status?("in_progress") && @lead.steps.in_progress.count > 1`
の条件は入れなくても、バリデーションが働いて削除できないようになっているはずです。
（destroyメソッドを見てみてください）

2020-11-21 07:30 UTC, taniryuu reviewed
まだコードレビューの途中ですが先に気になった点がありますのでコメントします。
綴りはloopが適切じゃないですかね？ブランチ名からもloopを使ってるようですが

2020-11-21 07:55 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      check_status_and_redirect_to(step, step, roop_ok)
その方がコード量が減るので良さそうです。53行目で直接params@[:loop_ok]を使うように変更しておきます。

2020-11-21 08:06 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      end
三項演算子で書くほうがスッキリしていますね。書き直しておきます。

2020-11-21 08:47 UTC, ruffini47 commented
やったことの③で
「③進捗新規作成時イベントページで進捗を削除するとき、それが唯一の進捗中進捗のときバリデーションで削除できないが、新規タスク生成フォームを使って新規タスク生成して終了するようにした。」
と書きましたが、よく考えると進捗を削除できないとき、削除ボタンを押して新規タスクを生成して辻褄を合わせるより、単に削除ボタンを表示しないほうがシンプルでユーザーにも分かりやすいことに後で気付きましたので、③の新規タスク生成に関する部分は丸ごと消去しました。

2020-11-21 08:48 UTC, ruffini47 commented
ループの綴りはroopでなく、loopですね。
修正しておきました。

2020-11-21 08:54 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>      else
loop_okがnilのとき、loop_ok == "true"はfalseになるんですね。書き直しておきます。

2020-11-21 08:56 UTC, ruffini47 commented on app/controllers/leads/steps_statuses_controller.rb
> +
このメソッドは上のコメントに書いたように、③のコードで削除対象になりましたので、削除しました。

2020-11-21 09:02 UTC, ruffini47 commented on app/views/leads/step_statuses/_destroy.html.erb
> +<% end %>
参考記事はありません。
config/routes.rbファイルでdestroy_step アクションをmethod deleteで定義したのでこのように書きました。
進捗を削除するときに新規タスクを生成しているためですが、
ここも③のコードで削除対象になりましたので削除しました。

2020-11-21 09:08 UTC, ruffini47 commented on app/views/leads/tasks/edit_continue_or_destroy_step.html.erb
> +
バリデーションが働いて削除できないため、@stepは進捗中か保留中に戻されるのですが、このとき進捗が進捗中、又は保留中にも関わらず、「未」のタスクも「完了」タスクも無いため、不正な状態になってしまいます。なので、削除できるときは削除し、出来ないときは削除ボタン自体を表示しないように変更しました。これが③で新規タスクを生成部分を丸ごと削除した理由です。

2020-11-21 09:19 UTC, ruffini47 commented
> これは、roopした場合に、エラーメッセージは表示されますか？
> 完了予定日などを空白にした際は、本来、エラーメッセージと共にrenderで戻って来れるのがベターと思いますが、それは難しかったでしょうか？
> 
単にrenderで戻ってくるのが難しかったのでこのようにしました。
①のタスク操作後のイベントページだけでなく、②の完了ボタン押印後のapp/views/stes_statuses/_indexのモーダルとの絡みがあるのでこのようにしました。

2020-11-21 09:20 UTC, ruffini47 commented
> まだコードレビューの途中ですが先に気になった点がありますのでコメントします。
> 綴りはloopが適切じゃないですかね？ブランチ名からもloopを使ってるようですが
ループの綴りはroopでなく、loopですね。
修正しておきました。

2020-11-21 09:21 UTC, ruffini47 commented
> まだコードレビューの途中ですが先に気になった点がありますのでコメントします。
> 綴りはloopが適切じゃないですかね？ブランチ名からもloopを使ってるようですが

ループの綴りはroopでなく、loopですね。
修正しておきました。

2020-11-21 13:39 UTC, ruffini47 commented
これまでのコメントに対する修正をして、pushしました。

2020-11-21 21:33 UTC, fumihisasuzuki requested changes
修正及び再考ありがとうございます。だいぶシンプルで機能的なコードになったように見えます！
1点だけ追加コメントありますのでお願い致します。

2020-11-21 21:33 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
>      else
renderが難しいのは理解しましたが、やはりUIを考えると、なんでループしているのか、フラッシュメッセージで構わないので何か表示がほしいですね・・・いかがでしょうか？

2020-11-22 02:05 UTC, taniryuu commented
確認しました！
コード、挙動ともに気になる点ありませんでした。

2020-11-22 02:06 UTC, taniryuu approved these changes

2020-11-22 13:09 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>      else
①のタスク操作後のイベントページや、②の完了ボタン押印後のapp/views/stes_statuses/_indexのモーダルで「タスク名」または「完了予定日」を空白にした時、タスク操作後イベントページにの現状でもapp/controllers/leads/application_controller.rbの45行目、`flash[:danger] = "#{flash[:danger]}#{@task.errors.full_messages.first}" if @task.present? && @task.errors.present?`によってフラッシュメッセージ「Taskは不正な値ですタスク名（または完了予定日）を入力してください」が表示されます。

2020-11-22 13:11 UTC, ruffini47 commented
新たなコメント確認しました。
フラッシュメッセージは現状でも表示されるので、変更箇所はありません。
マージ後にご確認ください。

2020-11-22 16:20 UTC, ruffini47 commented
上記とは別件で、Taskのテスト項目書を作成している途中に見つけた不具合を１つ修正しました。app/controllers/leads/application_controllerの新規タスク作成するとき、タスクの完了予定日を過去の日付にしたときにフラッシュメッセージを表示できていない不具合を見つけましたので修正しました。
時間の関係で今日は出来なかったのですが、同じフラッシュメッセージが表示されない不具合が上のコントローラーの進捗の完了予定日と、全く別の箇所ですが、進捗新規作成時と進捗直接編集時にも同様の不具合がありますので、報告させていただきます。

2020-11-23 00:07 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
>      else
そうなんですね！でしたら大丈夫です。失礼しました。

2020-11-23 00:11 UTC, fumihisasuzuki approved these changes
フラッシュメッセージの件は承知しました。マージ後確認させてください。
私からも追加でコメントはありませんが、上記不具合はどうされますか？
本プルリクで対応されるのか、別プルリクにするつもりなのか、ご教示ください。

本プルリクで対応されるならマージはお待ちしますし、
別プルリクで対応されるなら作業をtrelloに追加をお願い致します。

2020-11-23 11:52 UTC, ruffini47 commented
不具合の件ですが、別プルリクで対応させていただきます。
trelloに作業を追加しておきますので、よろしくお願いします。

2020-11-23 11:55 UTC, merged