完了予定日と完了日に過去の日付を入力するとフラッシュメッセージを表示する
taniryuu/Rer_Pro pull request #108
Opened 2020-11-23 13:27 UTC by ruffini47

## やったこと
①app/controllers/leads/application.rbのstart_stepで完了予定日に過去の日付を入力するとフラッシュメッセージを表示して警告する
②新規進捗（同時にタスク）作成時、完了予定日と完了日に過去の日付を入力するとフラッシュメッセージを表示して警告する
③進捗（同時にタスク）直接編集時、完了予定日と完了日に過去の日付を入力するとフラッシュメッセージを表示して警告する
## やらないこと
無し。
## できるようになること(ユーザ目線)
完了予定日と完了日に過去の日付を入力すると、フラッシュメッセージを受け取り確認することができる。
## できなくなること(ユーザ目線)
無し。
## 動作確認
app/controllers/leads/application.rbのstart_stepで進捗生成時、タスク生成時、新規進捗作成時、進捗直接編集時に完了予定日と完了日に過去の日付を入力するとフラッシュメッセージが表示されることを確認。
## その他
過去にprohibit_futureという名前のメソッドを作っていましたが、名称が適切性から、prohibit_pastという名前に変更しました。

2020-11-23 13:31 UTC, ruffini47 commented
テスト項目書作成時に発見しました、完了予定日と完了日に過去の日付を入力してもフラッシュメッセージを表示しない不具合を
修正しました。
レビューをよろしくお願いします。

2020-11-23 23:47 UTC, taniryuu approved these changes
確認しました！
テスト項目書作成時に気付くのはあるあるですね〜
私からは特に気になる点ありませんでした。

2020-11-24 00:12 UTC, fumihisasuzuki requested changes
全て後置ifにする方が、コード全体がスッキリすると思います。
下のような記事も尤もですが、このくらいの長さでしたら可読性もそんなに落ちないと思いますし、いかがでしょうか。
https://qiita.com/jnchito/items/4e47559a4c821474233a

2020-11-24 12:43 UTC, ruffini47 commented
確かにこの程度なら、後置ifにしたほうがスッキリするかと思います。
後置ifに修正します。

2020-11-24 13:39 UTC, ruffini47 commented
修正し、pushしました。
随分と見やすくスッキリしました。
確認をお願いします。

2020-11-24 21:31 UTC, merged