Refactering flash-message and Set template-validation
taniryuu/Rer_Pro pull request #110
Opened 2020-11-24 00:04 UTC by fumihisasuzuki

## やったこと
* テンプレートのバリデーションを追加
* フラッシュメッセージのリファクタリング（noticeをflashへ）
* サブヘッダーをこんな感じにしてみましたがいかがでしょうか。
（Dashbordやlinkは不要であれば最終的に削除して良いかと思います。）
![image](https://user-images.githubusercontent.com/56940903/100028977-8389fb80-2e33-11eb-9631-c6880f473af9.png)

## やらないこと
* update_user_idは次のプルリクで改善します。
## できるようになること(ユーザ目線)
* どのページからも案件の新規作成ができます。
## できなくなること(ユーザ目線)
* ステータスがテンプレートであるにも関わらず、テンプレートにチェックが入っていなかったり、進捗が進捗中になっていたりすること
## 動作確認
* 案件の編集（成功／失敗）、案件の削除を行い、正常に挙動することを確認しました。
## その他
* 特になし

2020-11-24 00:30 UTC, taniryuu requested changes
確認しました！
使われてないlinkも追加は容易なので削除していただいて大丈夫ですよ！

2020-11-24 00:30 UTC, taniryuu commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
ヘッダーのリンク編集ありがとうございます。
このリンク集良いと思います。

6行目の進行中の案件数は
`current_user.lead_count`
でも大丈夫かと思います。

あと4,8,11行目のaタグは消しておいてください。

2020-11-24 14:55 UTC, ruffini47 commented on app/views/leads/leads/_form.html.erb
> +    <%= form.check_box :template %>←ステータスに関わらずテンプレートとして使用する。
ここにチェックを入れた場合、どこのコードでこれを検出しますか？
「このテンプレートを使う」で選んだ場合も、ここのチェックの必要がありますか？

2020-11-24 15:14 UTC, ruffini47 approved these changes

2020-11-24 15:16 UTC, ruffini47 commented
確認しました。
大筋理解しました。
１点だけコメントさせていただきました。

2020-11-24 15:28 UTC, ruffini47 reviewed
確認しました。
大筋理解しました。
テンプレートを使ってみたのですが、例えば「テンプレート11」から案件を作成したとき、
進捗が１つしか作られないのですが、db/seeds.rbでは進捗が複数あったと思うのですが、そこは良いのでしょうか？

2020-11-24 15:30 UTC, ruffini47 reviewed
テンプレートを使ってみたのですが、例えば「テンプレート11」から案件を作成したとき、
進捗が１つしか作られないのですが、db/seeds.rbでは進捗が複数あったと思うのですが、そこは良いのでしょうか？

2020-11-24 15:41 UTC, ruffini47 reviewed
db/seeds.rbファイルをよく見ると案件１つに対して進捗１つしか書かれていないですね。
失礼しました。

2020-11-24 21:08 UTC, fumihisasuzuki commented on app/views/leads/leads/_form.html.erb
> +    <%= form.check_box :template %>←ステータスに関わらずテンプレートとして使用する。
> ここにチェックを入れた場合、どこのコードでこれを検出しますか？

template_controllerで検出しています。templateがtrueのものだけで一覧に出来るように絞り込みをかけています。

> 「このテンプレートを使う」で選んだ場合も、ここのチェックの必要がありますか？

「このテンプレートを使う」で選んだかどうかに関わらず、今からつくる（編集する）案件を今後テンプレートとして使用したい場合は、チェックを入れる必要があります。
しかし、テンプレートではない、通常の案件を作成する場合は、チェックを入れる必要はありません。
それをユーザーに伝えられるような表現に出来たらと思うのですが・・・
「ここにチェックを入れると、今後テンプレートとして使用できます。」とかの方がわかりやすいでしょうか。

2020-11-24 21:23 UTC, fumihisasuzuki commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
.lead_countはどこで定義されていましたっけ？ user_modelあたりが妥当かなと思ったのですが見つからず・・・

> あと4,8,11行目のaタグは消しておいてください。

<a class="nav-link" href="#">を丸ごと消しますね。

2020-11-25 01:41 UTC, taniryuu commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
ユーザー一覧とかで進捗中の案件を誰がどれだけ持っているかをいちいちSQLで持ってくるよりは、Userテーブルにカラム作った方が良いよねってことで追加したはずです。
現在はseedファイルの案件はカウントされてないので案件持ってないユーザーが案件作成時に+1されるようなロジックになってるはず？ですね。
DB定義書にもありますので是非とも

2020-11-26 03:13 UTC, fumihisasuzuki commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
カラムでしたか！忘れてました、失礼しました。
見てみます。

2020-11-26 03:30 UTC, fumihisasuzuki commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
DB定義書確認しました。
これ、.lead_countについて私は何か実装した記憶がないのですが、
新しく追加した.lead_countとlead_count_delayは、現在、いつ更新されるようになっているでしょうか？

2020-11-26 03:47 UTC, taniryuu commented on app/views/shared/_header_sub.html.erb
>      <a class="nav-link" href="#">
.lead_count、lead_count_delayともに現在は使う予定のページに使ってないです。
ですが今回ヘッダーに進捗中の案件数を表示するのはどうですか〜？ということですので
ここでlead_countを使わないと設定した意味がないと思いコメントしました。

更新される場面についてですが...２パターンありますね
案件CRUD時とNotifications#noticeメソッドでupdateするとか

2020-11-26 07:22 UTC, merged