Bug fix when changing value with developer tool
taniryuu/Rer_Pro pull request #117
Opened 2020-12-01 11:17 UTC by ruffini47

## やったこと
デベロッパーツールでフォームのvalue値を変更することにより、他のユーザーのタスクが生成できてしまうバグの修正。
具体的には、ストロングパラメータから(hidden_field経由の):step_idを消去して、`@task = Task.new(task_params)`の後に
`@task.update_attributes(step_id: @step.id)`としました。
## やらないこと
無し。
## できるようになること(ユーザ目線)
無し。
## できなくなること(ユーザ目線)
デベロッパーツールのフォームのvalue値を変更することにより、他のユーザーのタスクを生成すること。
## 動作確認
タスク新規作成、タスク更新、進捗の新規作成時の同時タスク生成、進捗の直接更新時のタスク生成、start_stepメソッド中のタスク生成が問題なくできることを確認しました。
## その他
特にありません。

2020-12-01 11:57 UTC, taniryuu approved these changes
手動で確認しましたがうまく動いてました！
これでOKかと思います。

2020-12-01 13:08 UTC, fumihisasuzuki requested changes
バグの対応おつかれさまです。
LeadやStepもここまで考えるとまだまだリファクタリングの余地がありそうですね・・・

気になったところがあったのでコメントしました。

2020-12-01 13:08 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +    @task.update_attributes(step_id: @step.id)
73行目を
`@task = @step.tasks.new(task_params)`
にすることで、74行目が不要にならないでしょうか？

2020-12-01 13:08 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +          @task.update_attributes(step_id: @step.id)
73, 74行目と同様

2020-12-01 13:08 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +      @task.update_attributes(step_id: @step.id)
49行目は必要でしょうか？
formの中のhiddenを削除したのでしたら、step_idをいじる余地はないわけですし、step_idをいじれない以上、step_idは@step.idのままなわけですから、この行はなくても成立するのでは、とふと思いました。

2020-12-02 14:26 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    @task.update_attributes(step_id: @step.id)
73行目を`@task = @step.tasks.new(task_params)`
にすることで、74行目が不要にになりましたが、それに伴い@taskが73行目で完全な形でcreateされますので、下のupdate_step_errorsメソッドの中で必要な@taskをcreateするのではなく、不必要な@taskを削除するように変更しました。

2020-12-02 14:28 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +          @task.update_attributes(step_id: @step.id)
上のコメントのように修正したのに伴い、ここでの185,186行目は削除しました。

2020-12-02 14:31 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +      @task.update_attributes(step_id: @step.id)
@taskのcreate時に`@task.update_attributes(step_id: @step.id)`のコードを実行しいるので、update時の49行目は不要ですね。49行目は削除しました。

2020-12-02 14:46 UTC, ruffini47 commented
進捗編集時のタスク生成のとき、上のコメントでも書きましたように、create時と同様に、update時に@taskを確定させるように変更しました。それに伴い無駄なupdate_attributesは削除しました。update_step_errorsメソッドで必要のない@taskを削除できるように、updateメソッドで@tasks_not_yet_present変数を導入し、update_step_errorsメソッドで使用しました。

2020-12-03 23:44 UTC, fumihisasuzuki requested changes
いつレコードに保存されているかについて、教えていただけると幸いです。

2020-12-03 23:44 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +    @task.update_attributes(step_id: @step.id)
ここも、@step.tasks.newにできませんか？

2020-12-03 23:44 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
>          end
下記３点コメントします。

１．この変更では、単純にTask.createを削除してしまっただけのように見えますが・・・どの行でタスクレコードを保存していますか？タスクの作成は以前通りにできるのでしょうか。
（saveまたはcreateをしないとDBには保存されないという認識でしたが・・・違っていたら教えていただけると嬉しいです。）

２．184行目のコメントは、コードをそのまま日本語で書くというよりは、要するにどういうことをしているのか、を書いていただけると後々助かります。
`stepにタスクがすでにある場合またはstepが「未」または「完了」のとき`にtaskを削除していることはコードを読めばわかるので。
`タスクがないとバリデーションに反する場合のみタスクを新規作成（それ以外は削除）`
や
`タスクを作る必要のない場合の処理`
など、コードの意図を書く方がいいかなと思いました。
（このあたりはプロジェクトの方針にもよるのかもしれませんが。）

３．削除した@taskに対して200行目で@task.invalid?していますが、これは特に問題にならないのでしょうか？

2020-12-04 03:42 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
>          end
進捗を編集するロジックが複雑化したり、タスクのCRUDを一緒に作るのが難しければ、登録or更新した進捗のステータスによってtasks#newにリダイレクトさせるのはどうですか？？

2020-12-04 12:44 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    @task = @step.tasks.new(task_params)
メソッド名には？で終わってもいいと思いますが、変数名の末尾に？を付けたら、railsに怒られました。

2020-12-04 13:06 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +    @task.update_attributes(step_id: @step.id)
この２行は`@task = @step.tasks.new(task_params)`で置き換えられます。その方が簡潔なので修正しておきます。

2020-12-04 13:21 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
>          end
1.についてですが、`@task = @step.tasks.new(task_params)`した時点でDBに保存されています。@task.destroyしない限り@taskのデータはDBに残り続けます。
2.の184行目のコメントですが、stepにタスクがある場合はそもそもタスクを作る必要がないので削除しています。
stepが「未」または「完了」のときはタスクがあるとバリデーションに反するので削除しています。
コメントは書き直しておきます。
3.につきましては確かに削除した@taskに対してエラーになるので`if @task.present? && @task.invalid?`が正しいコードです。書き直しておきます。
谷口さんのコメントですが、私も始めはtasks#newにリダイレクトさせようとしたことがありますが、そうするとsteps#updateのその後の処理がなされなくなるので、リダイレクトはできません。

2020-12-04 13:41 UTC, ruffini47 commented
鈴木（文）さんのコメントに対する修正をし、pushしました。
確認をよろしくお願いします。

2020-12-04 22:47 UTC, fumihisasuzuki requested changes
修正ありがとうございます。
newメソッドでもDBに保存されるのは意外でした・・・だとするとnew→saveの流れはバリデーションをわけるためだけに行われているのでしょうか？
現状、保存されるなら良いと思います。
newメソッドは確かバリデーションを無視できるので、それで最後にvalid?でバリデーションを実行するのは自然な流れと思います。

変数の命名規則について、再考いただければ幸いです。

2020-12-04 22:47 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +    @task = @step.tasks.new(task_params)
語尾に？をつけられるのはメソッドの話だったんですね。勉強になりました。ありがとうございます。

では、?は付けないにしても、@task~で始まるのは避けていただけないでしょうか？
現状、ぱっと見、複数のタスクが入っているように見えます。
私は、我流でやっていたときは前か後ろにflagをつけたりしていました。flagをつけるのはjavaなどの静的型付け言語でよく行われる手法でrubyではあまり用いられないそうなのですが。
こんなやりとりもありますし。
https://okwave.jp/qa/q9143938.html

2020-12-05 11:11 UTC, ruffini47 commented
確かに変数名として@tasks_not_yet_presentは複数のタスクが入っているように見えて、不適切ですね。@present_not_yet_tasksに変数名を変更しました。
確認をよろしくお願いします。

2020-12-06 04:00 UTC, fumihisasuzuki approved these changes
修正ありがとうございます。
コンフリクトを起こしているようですので修正いただけますか？

2020-12-06 07:30 UTC, merged

2020-12-06 07:30 UTC, ruffini47 commented
コンフリクト解消しました。
マージします。