Leadテストを行う中で気づいたこと
taniryuu/Rer_Pro pull request #123
Opened 2020-12-06 07:14 UTC by fumihisasuzuki

## やったこと
* Lead Editで直接ステータスを編集できないようにしました。そんなに気軽に変えるようなものではないので。
* Step create及びupdateでorderの値が、renderで戻った場合にずれてしまうのを修正しました。
* Lead Indexに遅延状況を追加しました。
* その他、LeadのCRUDに関する体裁の修正やflashメッセージの調整を行いました。
## やらないこと
* なし
## できるようになること(ユーザ目線)
* 進捗の作成、編集時にエラーが返ってきた際のストレス軽減（書いたフォームが維持される）
* 案件一覧で遅延状況がわかる。
## できなくなること(ユーザ目線)
* なし
## 動作確認
* テストの項目を行いました。
## その他
* なし

2020-12-06 08:08 UTC, ruffini47 commented on app/views/leads/steps/_form.html.erb
> +      <%= form.number_field :order, min: 1, max: steps_count + 1, value: present_value([params[:order_num], step.order, steps_count + 1]) %>
ここのpresent_valueとは何ですか？どこで定義されていますか？

2020-12-06 08:16 UTC, ruffini47 commented on app/views/leads/steps/edit.html.erb
> +<%= link_to '案件詳細に戻る', @step %> |
lead_steps_pathへのリンクは作らないのでしょうか？あった方が便利だと思いますが。

2020-12-06 08:28 UTC, ruffini47 commented on app/views/leads/index/_sort.html.erb
> +<%= link_to mark, sort: sort, user_searchword: params[:user_searchword], room_searchword: params[:room_searchword], customer_searchword: params[:customer_searchword], template_name_searchword: params
このようなソートのさせ方があったのですね。知りませんでした。

2020-12-06 14:15 UTC, taniryuu requested changes
コメントを残しましたので確認お願いします。

2020-12-06 14:15 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +    @task = Task.new(task_params)
#117 のプルリクで指摘されてた場所が戻ってると思うのですが何か理由があるんですか？
それかpullしてないだけでしょうか。

2020-12-06 14:29 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +        # 矛盾を解消
原因は不明ですがこの200〜205行目のコード２回繰り返してませんか？

2020-12-06 22:40 UTC, fumihisasuzuki commented on app/views/leads/steps/_form.html.erb
> +      <%= form.number_field :order, min: 1, max: steps_count + 1, value: present_value([params[:order_num], step.order, steps_count + 1]) %>
application_helper.rbで定義しました。

2020-12-06 22:47 UTC, fumihisasuzuki commented on app/views/leads/steps/edit.html.erb
> +<%= link_to '案件詳細に戻る', @step %> |
Step#index（進捗一覧）のことですよね？前回のミーティングでも申し上げましたが、あのページは本番環境では不要かなと考えていました。
進捗詳細でも、進捗の一覧は見られるので。

ただ、便利なら残しておいても良いかと思います。
あった方が便利なのはどんなときでしょうか？

2020-12-06 22:52 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +    @task = Task.new(task_params)
本当ですね、戻ってますね・・・
最後にプルしてコンフリクト解消しておいたのですが・・・

2020-12-06 22:59 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +    @task = Task.new(task_params)
もう一度プルしても、Already up to date.と表示されてしまいます・・・

とりあえずここは戻しておきました。
他にもあったらご指摘いただけると助かります。

2020-12-06 23:00 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +        # 矛盾を解消
ご指摘ありがとうございます！
修正します

2020-12-06 23:02 UTC, fumihisasuzuki commented
みなさんのコメントを折り込みました！
再度ご確認をお願いいたします。

2020-12-07 02:39 UTC, taniryuu approved these changes
修正ありがとうございます。
steps_controller.rbは差分サイトで確認したところ直ってました。
他ファイルも確認しましたが、私からはマージして大丈夫かと思います。

2020-12-07 14:12 UTC, ruffini47 commented on app/views/leads/steps/edit.html.erb
> +<%= link_to '案件詳細に戻る', @step %> |
'Back'ボタンは'案件詳細に戻る'に作り直されていたのですね。
'Back'ボタンが無くなったと勘違いしていました。
Step#indexは特に必要無いのでこのままで大丈夫です。

2020-12-07 14:13 UTC, ruffini47 approved these changes

2020-12-07 14:14 UTC, ruffini47 commented
コメント確認しました。
マージして頂いても大丈夫だと思います。

2020-12-07 14:16 UTC, merged