issue#115,#120,#121に対する修正
taniryuu/Rer_Pro pull request #124
Opened 2020-12-07 12:35 UTC by ruffini47

## やったこと
issue#115に対して、進捗直接編集時、進捗に「未」のタスクが無いときのみ新規タスクのフォームを表示するように変更しました。「未」のタスクが無いとき、進捗ステータスとして「進捗中」、「保留中」を選んだときのみ「タスク名」、「完了予定日」の入力を必須としました。（「完了」、「未」を選んだ時は空欄にしてもバリデーションエラーにならないようにしました。）
issue#120に対して、
## やらないこと
issue#122に対する修正は別プルリクにします。
## できるようになること(ユーザ目線)
進捗直接編集時、無駄な新規タスクフォームを入力しないで済む。（#115)

## できなくなること(ユーザ目線)
* 何ができなくなるのか?(あれば。無いなら「無し」でOK)
## 動作確認
* どのような動作確認を行ったのか? 結果はどうか?
## その他
* レビュワーへの参考情報(実装上の懸念点や注意点などあれば記載)

2020-12-07 13:02 UTC, ruffini47 commented
３つのissue(#115,#120,#121)に対する修正をしました。
レビューをよろしくお願いします。

2020-12-07 23:15 UTC, fumihisasuzuki requested changes
こうやって進んでくると、新たに気づきも出てきますね。
コメントしました。
よろしくお願い致します。

2020-12-07 23:15 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +  #before_action :set_new_task, only: %i(edit_continue_or_destroy_step edit_complete_or_continue_step edit_change_status_or_complete_task)
もし不要なコメントなら削除願います。

2020-12-07 23:15 UTC, fumihisasuzuki commented on config/routes.rb
> +        #patch 'complete_all_tasks'
これも不要なコメントであれば削除願います。

2020-12-07 23:15 UTC, fumihisasuzuki commented on app/views/leads/tasks/_tasks_index.html.erb
> +<% if @user.id == current_user.id %>
`@user.id == current_user.id`
は
`@user == current_user`
でも同じですのでお試しください。

2020-12-08 01:16 UTC, taniryuu requested changes
やはり進捗編集時にタスクの入力が不要になるだけでUIが大きく改善されてます。
修正ありがとうございます。
コメントさせていただきました！
是非ご検討ください。

2020-12-08 01:16 UTC, taniryuu commented on app/views/leads/tasks/_tasks_index.html.erb
> +<%  end %>
半角スペースが入ってるので削除お願いします。

2020-12-08 01:16 UTC, taniryuu commented on config/routes.rb
> +        get 'edit_continue_or_destroy_step'
この前話していたことがうまく伝わってなかったようなのでもう一度お話しします。

この37から39行目のviewページを１つのページとしてまとめてこの3つのviewをテンプレートとして変換し、
@stepの条件によって表示する内容をif分岐で表示分けする感じです。
なのでここは1行だけ
`get 'next_step(わかりやすければなんでも)'`
にして置いてこのviewに
```
if @step.status~~~
  render "edit_continue_or_destroy_step"
elsif ~~~
  render "edit_complete_or_continue_step"
elsif ~~~
  render "edit_change_status_or_complete_task"
end
```
と表示できれば良いのでは？という話でした。

2020-12-09 06:26 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +          flash[:danger] = "#{flash[:danger]}タスクの完了日に過去の日付を入力しようとしています。" if prohibit_past(@task.completed_date)
上記のようにstep.status?("completed")の場合の処理をここに入れました。

2020-12-09 06:27 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
>        end
1.~5.まで織り込んで修正しました。
ご確認ください。

2020-12-09 06:37 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> -        errors << @task.errors.full_messages if @task.present? && @task.invalid?
1.@taskのバリデーションは@taskを生成した`@task = step.tasks.new(task_params)`で実行されます。
2.@taskはpresence以外のバリデーションは設定しておらず、バリデーションエラーがあれば@task生成時に即座にエラーになるのでerrorsに代入する必要はないです。トランザクションでロールバックはしないです。

2020-12-09 06:38 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> -        errors << @task.errors.full_messages if @task.present? && @task.invalid?
上のコメントと同様です。

2020-12-09 08:11 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    end
1.については後置の方が良いですね。
2.ですが、今の場合、条件に合わなければ強制リダイレクトですので、条件をそのまま書いて、そうでなければ（unless)
強制リダイレクトという構造ですので、unlessを敢えて使ったほうがシンプルで可読性が高いと思います。.find_by(status: "not_yet")でなく、.not_yetのところは変更させて頂きました。
3.でコメントを書く場合も「～でない場合強制リダイレクト」が自然なコメントになります。

2020-12-09 08:22 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +  #before_action :set_new_task, only: %i(edit_continue_or_destroy_step edit_complete_or_continue_step edit_change_status_or_complete_task)
不要なので削除しました。

2020-12-09 08:23 UTC, ruffini47 commented on config/routes.rb
> +        #patch 'complete_all_tasks'
こちらも不要なので削除しました。

2020-12-09 08:26 UTC, ruffini47 commented on app/views/leads/tasks/_tasks_index.html.erb
> +<% if @user.id == current_user.id %>
同じモデルのidカラムの値を比較する場合はidが要らないのでね。
修正しました。

2020-12-09 11:18 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    def correct_not_yet_completed_nil_status
before_actionをまとめて１つにしました。条件は、「進捗新規作成時イベント」、「進捗完了時イベント」、「完了済進捗編集時イベント」のどれにも当てはまらないとき、強制的に@stepに遷移としました。

2020-12-09 11:20 UTC, ruffini47 commented on app/views/leads/tasks/_tasks_index.html.erb
> +<%  end %>
余分な半角スペースを削除しました。

2020-12-09 11:39 UTC, ruffini47 commented on config/routes.rb
> +        get 'edit_continue_or_destroy_step'
37から39行めのviewページに行く直前に各操作後のイベント条件で分岐しています。そのせっかく分離した条件を再びORでかき集めて、１つのviewページに集めてそれを更にif分岐するのは、ifを分岐→集める→分岐と2回分多く分岐させているので無駄な分岐を2回分していることになります。なので

2020-12-09 12:02 UTC, ruffini47 commented
鈴木（文）さんと谷口さんのコメントに対しての修正をし、pushしました。
ご確認をよろしくお願い致します。

2020-12-09 12:24 UTC, taniryuu commented on config/routes.rb
> +        get 'edit_continue_or_destroy_step'
なるほど。
直前でも分岐をかけてたんですね。

今のところデメリットも見受けられないので現状このままにしましょうか

2020-12-09 12:27 UTC, ruffini47 commented on config/routes.rb
> +        get 'edit_continue_or_destroy_step'
現状のまま行きたいと思います。

2020-12-09 13:58 UTC, taniryuu requested changes
コメント残しましたので確認お願いします。

2020-12-09 13:58 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +      if !(@step.tasks.not_yet.blank? && @step.tasks.completed.blank?) &&
この!を使用した否定文はblank?↔︎present?を入れ替えるだけで使用せずに済むと思います。
なので253行目以外は使用せずに済むかと

参考:https://qiita.com/aeroastro/items/b58228decb7094af7594

2020-12-09 15:09 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +      if !(@step.tasks.not_yet.blank? && @step.tasks.completed.blank?) &&
!AでAの中身を変えることで!を使わない表現にできることは承知していますが、AでもBでもCでもないときを表現したくてif !A && !B && !Cと記述しました。'edit_continue_or_destroy_step'の条件としての『進捗に「未」のタスクが無く、「完了」のタスクも無く』を崩さずに表現したAを変えたくなくて敢えて!Aとしたのですが。

2020-12-10 02:28 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +      if !(@step.tasks.not_yet.blank? && @step.tasks.completed.blank?) &&
なるほどです。理解できました。
unlessを使用するよりはまだ良いかもしれないですね。
このメソッドでリダイレクトされる時はURLを直接入力された時かと思うのですが
flashメッセージの追加は考えてますか？

2020-12-10 09:25 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +      if !(@step.tasks.not_yet.blank? && @step.tasks.completed.blank?) &&
基本的に、否定の否定は避けるべきと思っています。
それでも「AでもBでもCでもないときを表現」するなら、
A, B, Cをメソッド化する手もあると思います。

ただ、要するに、このメソッドは、step.statusとタスクの関係が正しければ詳細ページに強制リダイレクトさせるメソッドですよね？
それらの関係が正しくない条件というのがA, B, Cと３種類あるので、「敢えてif !A && !B && !Cと記述」されているのだと思いますが、
逆に正しい条件をA, B, Cとすれば素直にif A && B && Cと表現できると思います。いかがでしょうか？

2020-12-10 09:25 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +    end
別のところでもコメントしましたが、この条件式が頻繁に出てきているならメソッド化する方が良いかもしれないですね。
その方が今後の変更にも強くなると思います。

「矛盾を解消する必要のある条件」が３つあるということですよね。
メソッド名をわかりやすくする必要がありますが、そうすれば、unless (メソッド名)という単純なコードにできそうです。

2020-12-10 09:28 UTC, fumihisasuzuki requested changes
ありがとうございます。さらにすっきりしました。

同じ条件式が何度も出てきているように見受けられるので、メソッド化するのはいかがでしょうか。

2020-12-10 12:08 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +      if !(@step.tasks.not_yet.blank? && @step.tasks.completed.blank?) &&
タスク操作後のイベントの条件をメソッド化しました。他の箇所では否定形でなくそのままの形の条件を使っているので、メソッド化も否定をメソッドに織り込むのではなく、そのままの条件にしました。なのでここのcorrect_statusメソッドでは、やはり`if !A && !B && !C`の形の条件になっています。

2020-12-10 12:30 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> -        errors << @task.errors.full_messages if @task.present? && @task.invalid?
taskだけバリデーションエラーを発生させて、debuggerでerrorsを表示させると確かに「[["Tasksは不正な値です"]]」しかでないですね。@task.errorsだと「{:name=>["を入力してください"], :scheduled_complete_date=>["を入力してください"]」と中身が表示されます。やはりerrors変数に@task.errorsを代入するほうが正しいバリデーションエラーに対処する方法なのですね。`errors << @task.errors.full_messages if @task.present? && @task.invalid?`の一行をトランザクションの最終行に追加しておきます。

2020-12-10 12:31 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> -        errors << @task.errors.full_messages if @task.present? && @task.invalid?
ここにも`errors << @task.errors.full_messages if @task.present? && @task.invalid?`を追記しておきます。

2020-12-10 12:36 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    end
下のコメントにも書きましたが、条件をそのままメソッド化しました。他の箇所でそのままの条件を使っているからです。なのでcheck_statusメソッド内ではif !A && !B && !Cの形になっています。

2020-12-10 12:52 UTC, ruffini47 commented
①タスクのバリデーション時にerrors変数に@task.errorsを代入する一文をleads/steps_controllerのsave_step_errorsメソッドとupdate_step_errorsメソッドに追加しました。
②また、check_statusメソッド中の条件式の部分をメソッド化しました。そのメソッドはcheck_status_and_get_urlメソッド内で利用しています。
③check_statusメソッドで強制リダイレクト時にフラッシュメッセージを表示させるようにしました。
以上3点修正しました。

2020-12-11 05:45 UTC, fumihisasuzuki approved these changes
ありがとうございます。確認しました。よくなったと思います！

2020-12-11 08:52 UTC, taniryuu approved these changes
確認しました。
修正ありがとうございます。
途中リファクタリングできそうなところを見つけましたが、修正は次回でもOKかと思います。
結構キレイにまとまったかと思いますのでマージします。

2020-12-11 08:52 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +  before_action :set_new_task, only: %i(edit_continue_or_destroy_step edit_complete_or_continue_step edit_change_status_or_complete_task)
set_new_taskはshowアクションでも使用できそうですね。

2020-12-11 08:52 UTC, merged

2020-12-13 05:57 UTC, ruffini47 commented
close #115