通知確認ボタン通知受信者以外クリック不可
taniryuu/Rer_Pro pull request #129
Opened 2020-12-14 11:43 UTC by taniryuu

## やったこと
issue #119 の修正
## やらないこと
特になし
## できるようになること(ユーザ目線)
通知受信者以外のユーザーは表示自体はされるがクリックしても反応しないようdisabledを付与しました。
## 動作確認
実際にページを見て、クラスが付与されていること、正しい受信者は正常に確認できることを確認しました。
## その他
コードレビューよろしくお願いします。
マージされましたら、本番環境にもpushしようかと思います。

一緒に今回の変更と同時にissueの自動closeをできるかチェックします。
close #119

2020-12-14 21:58 UTC, fumihisasuzuki requested changes
細かいコメントで恐縮ですが、後学のためにご意見あればお聞きしたいので、よろしくお願いします。

2020-12-14 21:58 UTC, fumihisasuzuki commented on app/helpers/users_helper.rb
> +  end
これは、
`if user == current_user`
と書かなくてはならない箇所を、
`if correct_user?(user)`
と書けるようにしたヘルパーメソッドということですね？
最初、ほとんどコード量も減らないしどうしてわざわざ作ったのかと思いましたが、rails的な書き方になってより直感的になったという点で可読性を上げるという意図ですかね？

３点コメントさせてください。

１．「引数のユーザーがcurrent_userと同じか判定」するメソッドですので、
`correct_user?`（正しいユーザー？）
というよりは、
`current_user?`（現在のユーザー？）
とした方がより内容をダイレクトに表していると思うのですが、いかがでしょうか。

２．これは、` ? true : false`を削除して、単に、
```
  # 引数のユーザーがcurrent_userと同じか判定
  def correct_user?(user)
    user == current_user
  end
```
では動きませんか？
上記で動くようなら、８〜10行目のdelete_judgmentメソッドもリファクタリングできますね。

３．この条件は色々なところで使われているので、今後リファクタリングのしがいがありますね。
ここは個人で気付いたらやっていくことにしますか？
それともまとめて実施されますか？

2020-12-14 21:58 UTC, fumihisasuzuki commented on app/views/leads/steps/show/_notice.html.erb
> +    <% superior = @users.find(@user.superior_id) %>
superiorを代入する場所についてコメントさせてください。
まず端的に結論だけ申し上げると、現在4行目で代入しておりますが1行目にしませんか？

知らない変数を見た人が「この変数には何が代入されているのだろう」と思った際に、確認する場所は次の順番だと思います。

> １．直上
> ２．改行で仕切られているブロックの最初
> ３．ファイルの最初
> ４．直接関係するcontroller, model, helperなどの別のファイル
> ５．上記が継承しているcontroller, model, helperなど、より影響力の広いファイル

（これは私の考えなので、何か異なるソースがあればぜひ教えてください。）

5行目のsupreiorを見た人はすぐ上で代入しているのでわかりやすいですが、
9行目のsupreiorを見た人が、ブロックの途中で代入されているsupreiorを見つけるのは少々面倒です。
（今回はまだ9行目なのでそんなに苦労はないかと思いますが、考え方として、です）

また、今後１〜3行目でsupreiorを使えない、というデメリットもあります。
（これも、今回はたった3行なのでもし使う際に代入箇所を移動すれば良いのですが、これも考え方として、です）

したがって、4行目よりは1行目で代入しておく方が、後々のメンテナンスコストが下がるのでメリットが大きいと考えますが、いかがでしょうか？

2020-12-14 22:44 UTC, taniryuu commented on app/helpers/users_helper.rb
> +  end
1,
迷いましたがapplication_controller.rbに似たcorrect_userが定義されてるのでcurrent_user?みたいに特別変更するよりは、よせていこうかなと思いました。

2,
動き自体はご指摘のコードでも大丈夫でしょうし、わかりやすいコメントもついていればなお良いと思いますが、あえて消すよりも明示的にbooleanを返すメソッドでわかりやすくないですか？

3,
引数を設けることでcurrent_userと@userに限定しなくてよくなるかと思い作りました。
個人で気づいた時にリファクタリングしていけば良いかと思います。

2020-12-14 22:48 UTC, taniryuu commented on app/views/leads/steps/show/_notice.html.erb
> +    <% superior = @users.find(@user.superior_id) %>
場所がわかりやすいのは純粋に良いですね。
変更します。

2020-12-14 23:42 UTC, taniryuu commented
@fumihisasuzuki 
コメントありがとうございます。
変数の定義を1行目に持っていく上で、if分岐をしてましたのでstep#showのrenderに分岐を挿入しております。

ヘルパーメソッドの名前ですが、引数のユーザーが現在ログインしているユーザーと同じかをチェックしてるのでcurrent_user?(現在のユーザー？)よりcorrect_user?（正しいユーザー？）の方が意味合い的に合ってる気がしてきました。

2020-12-15 15:10 UTC, ruffini47 approved these changes
確認しました。
私からは特に気になる点はありませんでした。

2020-12-15 15:22 UTC, ruffini47 commented on app/views/leads/steps/show/_notice.html.erb
> +      <%= link_to "確認", change_limit_check_step_path(step), method: :patch, data: { confirm: "期限の変更を確認します。"}, class: "btn btn-sm btn-primary #{"disabled" unless correct_user?(superior) }" %>
1点だけ気になったのですが、`#{"disabled" unless correct_user?(superior) }"`でdisabledは""で囲わなければならないでしょうか？何となく気になったのでコメントしました。

2020-12-15 21:57 UTC, fumihisasuzuki commented on app/helpers/users_helper.rb
> +  end
1. システム内で、「correct_user」が「userがcurrent_user」であることで統一がとれてたんですね！だったら、確かによせていくことで良いと思います！
2. 可読性を優先したということですね。そうですね、私個人的には、メソッド名に「?」がついていることからboolean型であることは明示されているので別にいらないかなと思ってしまったためコメントさせていただきました・・・。もちろん、最終的にはPM判断で結構です。
3. 承知しました、気づいたところからリファクタリングしていきます。

2020-12-15 22:22 UTC, fumihisasuzuki approved these changes
@taniryuu さん
  返信しました。また、修正ありがとうございます。確認しました。スッキリしたと思います。

@ruffini47 さん
approvalだったのでマージしてしまっても良いかと思いましたが、コメントされていたので一応やめておきました。
谷口さんからの返信を確認したら、マージしていただけると幸いです。

2020-12-16 00:26 UTC, taniryuu commented on app/views/leads/steps/show/_notice.html.erb
> +      <%= link_to "確認", change_limit_check_step_path(step), method: :patch, data: { confirm: "期限の変更を確認します。"}, class: "btn btn-sm btn-primary #{"disabled" unless correct_user?(superior) }" %>
試しに""を外してページを再読み込みしてみたのですが、disabledがメソッドに誤認されるみたいでActionView::Template::Error、disabled？変数・メソッドは定義されてませんと表示されます。
文字列として扱わないとダメみたいです

2020-12-16 12:00 UTC, ruffini47 commented on app/views/leads/steps/show/_notice.html.erb
> +      <%= link_to "確認", change_limit_check_step_path(step), method: :patch, data: { confirm: "期限の変更を確認します。"}, class: "btn btn-sm btn-primary #{"disabled" unless correct_user?(superior) }" %>
そうなんですね。勉強になりました。
ありがとうございます。

2020-12-16 12:01 UTC, merged