issue #128に対する修正と各イベント操作後のページのbefore actionの変更
taniryuu/Rer_Pro pull request #132
Opened 2020-12-17 13:37 UTC by ruffini47

## やったこと
①issue   #128に対する修正
具体的には、タスクの矛盾を解消するページから@stepへ戻った時、矛盾する状態だったら再び矛盾を解消するページにredirectするようにしました。
②3条件まとめて判別していたcheck_statusメソッドを、1つ1つ分けなければならない状況に対応するため、3条件を分けたcorrect_continue_or_destroy_step_status、correct_complete_or_continue_step_status、correct_change_status_or_complete_task_statusメソッドをそれぞれbefore actionで実行するようにしました。
## やらないこと
issue#130に対する修正はまだやっていません。
## できるようになること(ユーザ目線)
戻るボタンで戻った時でも矛盾の無い状態にするページにリダイレクトされる。
## できなくなること(ユーザ目線)
タスク―ステップの矛盾した状態にすること。
## 動作確認
①タスク操作後のイベントページから戻るボタンを押し、@stepにページ遷移後、再読み込みボタンを押したとき、タスク操作後のイベントページにリダイレクトされること。進捗完了時イベントページ、完了済進捗編集時イベントページから戻るボタンを押し、@stepぺージに遷移後、完了済の進捗を現在の進捗にしたとき、タスク操作後のイベントページにリダイレクトされること。
②3条件のうち一つに合致しているとき、その他の条件のページへリダイレクトを要求したら@stepへリダイレクトされること。
## その他
3条件まとめて判別していたcheck_statusメソッドを3条件を分けた理由につきましては、下で説明させていただきます。

2020-12-17 13:46 UTC, ruffini47 commented
3条件まとめて判別していたcheck_statusメソッドを3条件を分けた理由ですが、どの条件にも合致していない場合から、3つの内1つの条件のページを要求したとき、@stepへ強制リダイレクトされる点は変わっていませんが、しかし、どれか一つの条件に合致している状態から、その他の条件のページを要求したとき、3条件をまとめて判別していた場合、その他の条件のページへ間違ってリダイレクトされることになります。（３条件どの条件にも当てはまらない場合のみ@stepへ強制リダイレクトされる仕様でしたから。）それを防ぐために１つ１つを分けて判別するように修正しました。

2020-12-17 13:48 UTC, ruffini47 commented
issue#128の修正と各イベント操作後のページのbefore actionメソッドを３つに分けることをしました。
レビューをお願い致します。

2020-12-18 00:02 UTC, taniryuu requested changes
コメント残しました。
確認お願いします。

動作は完璧でした！

2020-12-18 00:02 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +    def contradiction_detection(step)
このメソッドは何をしているかなどコメントが欲しいです。

2020-12-18 00:02 UTC, taniryuu commented on app/controllers/leads/steps_controller.rb
> +      if !continue_or_destroy_step?(step)
ここまで分かりやすくなると寧ろunlessでも良い気がします。

2020-12-18 12:12 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +    def contradiction_detection(step)
コメントを付け忘れていました。
コメントを付けましたのでご確認下さい。

2020-12-18 12:13 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +      if !continue_or_destroy_step?(step)
unlessの方が分かりやすいですね。
修正しておきました。

2020-12-19 14:44 UTC, ruffini47 commented
谷口さんのコメントに対する修正をし、プッシュしました。
ご確認下さい。

2020-12-19 14:51 UTC, taniryuu approved these changes
確認しました！
変更ありがとうございます。
私からはOKかと思います。

2020-12-19 20:53 UTC, fumihisasuzuki approved these changes
メソッドを３つにわけることによって可読性も著しく向上したように思います。
コードをスッキリまとめてくださってありがとうございました。

2020-12-19 20:54 UTC, merged