Create Task-model and set validation
taniryuu/Rer_Pro pull request #45
Opened 2020-08-31 13:18 UTC by ruffini47

Taskモデルを作成しました。Stepモデルと1対多の紐づけをしました。
null FALSE, default値を設定しました。nameのlengthを60文字まで、memoのlengthを400文字までとする
validationを追加しました。nameとscheduled_complete_dateはpresence :trueにしたほうがよろしいでしょうか？

2020-08-31 13:49 UTC, taniryuu commented on app/models/task.rb
> +  validates :name, length: { in: 0..60 }
https://qiita.com/wonder_meet/items/fa804f0d436a29c97460

私も最近教えていただいたのですがpresence: trueにしないと""(空文字)でもsaveできてしまうようです。
memoに関しては空文字でも大丈夫ですがnameは少しまずいので追記をお願いします。

2020-08-31 13:52 UTC, taniryuu commented on db/migrate/20200831123021_create_tasks.rb
> +      t.string :name, null: false, default: ""
model/task.rbに書いた参考記事で言うとdefault: ""も弾けるのでここは時間が空いたら必要かどうか検証してみてください。

2020-08-31 13:58 UTC, taniryuu commented
確認しました！

model/task.rb
一点だけ修正お願いします。
他は問題なさそうなので修正済みしだいマージしようと思います。

2020-09-01 03:38 UTC, fumihisasuzuki requested changes
enum使ったことなければ教えてください！（参考資料探します）

2020-09-01 03:38 UTC, fumihisasuzuki commented on db/migrate/20200831123021_create_tasks.rb
> +      t.integer :status, null: false, default: 0
statusカラムは、モデルファイルにenumの設定をお願いできますか？
stepモデルやleadモデルを参照ください。

2020-09-01 10:42 UTC, ruffini47 commented on db/migrate/20200831123021_create_tasks.rb
> +      t.integer :status, null: false, default: 0
すみません。enumを使ったことがありません。参考資料を教えていただけますか？

2020-09-01 10:57 UTC, ruffini47 commented on db/migrate/20200831123021_create_tasks.rb
> +      t.string :name, null: false, default: ""
わかりました。検討してみます。

2020-09-01 10:59 UTC, ruffini47 commented on app/models/task.rb
> +  validates :name, length: { in: 0..60 }
name と scheduled_complete_date に presence: true を追記しました。

2020-09-01 12:12 UTC, ruffini47 commented on db/migrate/20200831123021_create_tasks.rb
> +      t.integer :status, null: false, default: 0
"activerecord enum" でググり、鈴木（文)さんのapp/models/step.rbを参考に
別pull request "Add enum status to task model #46"でプルリクを上げさせてもらいました。

2020-09-01 12:28 UTC, taniryuu commented
#46に挙げていただいたプルリクと変更差分がほぼ被ってますのでこちらのプルリクは閉じさせていただきます。

2020-09-01 12:28 UTC, closed without merging

2020-09-01 21:06 UTC, fumihisasuzuki commented on db/migrate/20200831123021_create_tasks.rb
> +      t.integer :status, null: false, default: 0
ありがとうございます。そちらのプルリクで確認します！