Feature/devise user create
taniryuu/Rer_Pro pull request #47
Opened 2020-09-02 02:09 UTC by taniryuu

やったこと

・企業内ユーザー新規登録ロジック作成
　　管理者からユーザーの登録をした際の挙動を作成

・deviseのauthenticate_userを切り出した
　　今後before_action :authenticate_user!を適用させたい場合はcontrollerの継承元クラスをUsers::ApplicationControllerに変更する仕様にしました。参考: https://qiita.com/ryuuuuuuuuuu/items/bf7e2ea18ef29254b3dd

・管理者sign_upと一般ユーザーsign_upを切り出す
　　deviseの制御が難しい挙動と混ざるので分けました。

・汎用性の高いエラーメッセージテンプレート作成
　　deviseのテンプレートしかなかったので作成。
　　users#newのテンプレートを真似してもできますが一応使い方の参考は自分のメモですが参考に残しておきます。
　　参考: https://qiita.com/tr76aquarius/private/50ae578cb8b6dcfd6033
　
・企業新規作成&管理者とそれ以外のUser作成ロジック,マイグレーションファイル修正
　　フェーズ2に回す予定でしたがusers#create,users/registrations#createを作成時点で完成してしまったので作成。
　　マイグレーションについては該当行にコメント残しておきます。

以上、量が多くなりましたがレビューよろしくお願いします。

2020-09-02 02:13 UTC, taniryuu commented on db/migrate/20200819030301_devise_create_users.rb
> +      t.integer :superior_id
ここのnull: falseとmodelのpresense: trueが両方残っている時、
null: falseを残してpresense: trueを消した時のエラー文が全く同じでした。
エラーの内容はSQLの登録時にnull:falseになって登録できないようなエラー文でした。
presense: trueを残してnull: falseを消すとmodelの自作したメソッドが効いて登録可能となりましたのでこちらを採用。

2020-09-02 02:16 UTC, taniryuu commented on app/models/user.rb
> +  def start_up_create_user?
企業を登録後、管理者として自分のUser情報を登録する際に通知送信先に誰も指定できないためこのメソッドを作成しました。
19行目の書き方でこの条件がtrue時だけpresence: trueが外れるようになってます。

2020-09-02 12:51 UTC, ruffini47 commented on app/controllers/users/registrations_controller.rb
> +  before_action :current_user_admin?, only: %i(new create cancel)
%iの後のカッコは"["でなく"("で良いのでしょうか？
またonly: %i(new create cancel) はonly: [:new, :create, :cancel]とどう違うのでしょうか？　

2020-09-02 13:18 UTC, taniryuu commented on app/controllers/users/registrations_controller.rb
> +  before_action :current_user_admin?, only: %i(new create cancel)
この書き方で:と,を省略した書き方になります。
他にも汎用聞くと思いますがまだ試したことないので現状ここだけ書いてます。
多くなればなるほど扱いが楽になりますよ
参考:https://qiita.com/mogulla3/items/46bb876391be07921743

2020-09-02 13:19 UTC, fumihisasuzuki commented on app/controllers/users/registrations_controller.rb
> +  before_action :current_user_admin?, only: %i(new create cancel)
％記法と呼ばれる記載方法で、意味は全く同じようです。
https://qiita.com/mogulla3/items/46bb876391be07921743

"("で問題ないと思います。

2020-09-02 13:37 UTC, fumihisasuzuki commented on app/models/user.rb
> +  def start_up_create_user?
なるほど、そういった不具合が起こるとは予想していませんでした。
19行目は条件式がtrueのときにpresense: trueが発動するように見えますが・・・この方法で、回避できるんですね？

ただ、そうですね・・・この方法だと、最初に一般ユーザーを登録するようなケースが意図せずに生じてしまった場合に、イレギュラーなレコードが作成されてしまう恐れがありませんか？
また、別のユーザーを登録したあと、最初のユーザーの編集をした際に改めてバリデーションにひっかかるというのはユーザーにとってストレスになるような気がします。
例えば、
１．admin: trueのユーザーは、superior_id空欄可。
２．superior: trueのユーザーは、自身を設定可。
３．両方falseのユーザーは、自分以外のsuperior_idの設定が必須
のような設定はいかがでしょうか？バリデーションには１を記載するのはいかがでしょうか？
そうすることでDBに一貫性が持てるような気がします。

2020-09-02 13:48 UTC, fumihisasuzuki commented
複雑なコーディング作業、おつかれさまです。
ちょっと私の理解不足で申し訳ありませんが、
「管理者sign_upと一般ユーザーsign_upを切り出す」
「企業新規作成&管理者とそれ以外のUser作成ロジック」
の2点が、要するに何をしているのか、がわかりにくく、近いうちに口頭で説明していただけると嬉しいです。
（管理者とそれ以外で、コントローラーを分けた、といった感じでしょうか・・・？）

2020-09-02 14:06 UTC, taniryuu commented on app/models/user.rb
> +  def start_up_create_user?
この1の書き方はscopeで実装できますかね？まだ試してもいないのですが。

流れとしては、
企業登録時点から最初のUser登録(form側で管理者= true)→企業に属したUserの作成(form側で管理者= false)といった感じです。
この辺りは実際に触ってみた方がわかりやすい気もします。(アクセス制限などはまだ書けてないです。)

2020-09-02 14:17 UTC, taniryuu commented
説明がわかりにくくて済みません。

・管理者sign_upと一般ユーザーsign_upを切り出す
　登録フォームを分けてます。なのでcontrollerもdevise側とUsers側で2つ作成してあります。
　管理者権限を強制的にtrueになるformと強制的にfalseになるformです。

・企業新規作成&管理者とそれ以外のUser作成ロジック
　Companyのnewとcreateアクション作成、その後すぐ管理者User作成formにredirect_toされて↑のformに飛び、
　作成後管理者以外のUserを作成するUsers#newとcreateアクションの作成をしました。

　またわからなければ口頭と実際の画面遷移を行いながら説明します。

2020-09-02 15:13 UTC, ruffini47 commented on app/controllers/users/registrations_controller.rb
> +  before_action :current_user_admin?, only: %i(new create cancel)
%iの意味が分かりました。
ありがとうございます。

2020-09-03 04:06 UTC, fumihisasuzuki requested changes
登録フォームをそもそも分けたんですね！
確かにそれがいいかもしれません。フェーズ２以降の内容だったかもしれませんが、今できるならやってしまっていいですしね。
企業内の管理者の作成：システム開発者のみ可能
企業内の上長及び一般ユーザーの作成：企業内の管理者のみ可能
みたいな住み分けができそうですね。

コードにもコメント追記しました！

2020-09-03 04:06 UTC, fumihisasuzuki commented on app/models/user.rb
> +  def start_up_create_user?
「Users#newで作成しているformのアクセス自体を他に同じ企業内にUserが存在しない場合に発火する」のは良い方法かもしれません。
ご提案の流れは、
１．Create company
２．同じ企業内にUserが一人もいないのを条件として→「管理者をnewできるフォーム」にアクセス可
３．管理者がcreateできたら、管理者としてログインして、そこから他のユーザーをcreate可能
といった流れでしょうか？

2020-09-03 04:36 UTC, taniryuu commented
その流れになってます。
まだまだ問題が積まれてますがそこはフェーズ2以降に作ろうかと思ってます。
(企業登録→管理者登録せずにブラウザを閉じたら企業だけ登録されて管理者を登録できなくなる)

ここの管理者をどういった運用にしていきたいのかが企業によってまちまちだと思うんですよね...
管理者兼上長として普通に案件も登録するし通知も受け取るなら通知の送信先も指定したりとしたいでしょうし。
専用の選択タブなのでpresence: true, unless: -> { admin? }をつけても半強制で指定させる作りになるのですが
一応つけても問題なさそうなので修正しておきます。

2020-09-03 05:15 UTC, taniryuu commented on app/models/user.rb
> +                                          unless: -> { admin? }
これでも動作しました。

2020-09-03 05:17 UTC, taniryuu commented on app/models/user.rb
> +  validate :active_superior_in_the_same_company, on: :update, if: :start_up_create_user?
管理者登録後に管理者の情報を編集する際このメソッドでエラーが出たのでこちらにもif: :start_up_create_user?を付与しました。
UserのIDがないですといったエラーの内容でした。

2020-09-03 09:45 UTC, fumihisasuzuki requested changes
何度も申し訳ありません。
できるだけ、admin?かどうかやsuperior?かどうかでロジックを分けていった方がシンプルかなと思い、コメントさせていただきました。（条件分岐が増えれば増えるほど例外の処理が大変で複雑になります。）
いかがでしょうか？

2020-09-03 09:45 UTC, fumihisasuzuki commented on app/models/user.rb
> +  validate :active_superior_in_the_same_company, on: :update, if: :start_up_create_user?
superior_idがnilになっていることによって生じるエラーと推察致します。
start_up_create_user?のメソッドを多用することになると、今後も、最初のUser.createと2回目以降で挙動を分け続けることになって後々不便になりませんかね？

せっかく、sign_upのページも「管理者とそれ以外」で分けたんですから、こちらのバリデーションも「管理者とそれ以外」で分けられれば、その方が、ロジックがシンプルになると考えます。
すなわち、if: :start_up_create_user?を使うのではなく、unless: -> { admin? }を使うことでエラーを回避できないでしょうか？

2020-09-03 10:23 UTC, taniryuu commented on app/models/user.rb
> +  validate :active_superior_in_the_same_company, on: :update, if: :start_up_create_user?
エラーの回避はできました。

この:active_superior_in_the_same_company自体が自分の会社内に存在する且つactiveなstatusのユーザー以外の入力を弾くメソッドですが丸ごとunless: -> { admin? }と設定しても大丈夫ですかね？他の会社に所属しているユーザーIDに更新できたりしませんかね。

2020-09-03 10:38 UTC, taniryuu commented
コメントありがとうございます。

このon: :updateの後ろに管理者のみif: :start_up_create_user?を通すような動きにすれば
管理者以外のユーザーにif: :start_up_create_user?が使われないのでその書き方を探してみましょうかね？

2020-09-03 11:40 UTC, fumihisasuzuki commented
次のように書き換えるのはいかがでしょうか？という意味でした。
validate :active_superior_in_the_same_company, on: :update, unless: -> { admin? }
validates :superior_id, presence: true, unless: -> { admin? }

上記の書き方で、最初におっしゃっていた
「企業を登録後、管理者として自分のUser情報を登録する際に通知送信先に誰も指定できない」
という問題が回避できるのでは？という提案です。
上記書き方だと、別の問題が発生するんでしょうか？？

2020-09-04 05:15 UTC, merged