Feature/devise users form
taniryuu/Rer_Pro pull request #57
Opened 2020-09-07 15:23 UTC by taniryuu

このプルリクのメインはUserのnew,create,edit,updateのアクセス制限がメインです。
主に管理者とそれ以外のユーザーでアクセス制限、フォームの編集権限を分けています。
deviseで自動的に裏で動くアクセス制限の補完を行いました。

このプルリクと一緒にbootstrapのバージョンを上げましたがchatworksに書いた理由の他にこの後のdestroyアクションを作成する際にモーダルを使用するのでここでバージョン指定も含めたプルリクとなりました。

以上、確認をよろしくお願いします。

2020-09-07 15:26 UTC, taniryuu commented on app/controllers/users/registrations_controller.rb
> +    if by_admin_user?(params) && resource_class.to_adapter.get(params[:id]).try(:id)
ここの&&に続く１文を入れないとURLに直接idを入力した際にユーザーが存在しなかった場合にエラーを起こします。

2020-09-07 22:41 UTC, fumihisasuzuki requested changes
複雑なログイン認証まわりの実装、ありがとうございます。
苦労して色々工夫してくださっているのが伝わって参ります。

細かいところですが、コメント致しました。よろしくお願い致します。

また、bootstrapなど、変更箇所が全く異なる場合は、次回からプルリクを分けていただけるとレビューしやすく、大変助かります。

2020-09-07 22:41 UTC, fumihisasuzuki commented on app/controllers/application_controller.rb
> +    end
"user_signed_in? && " は必要でしょうか？
authenticate_user!が前に来るなら不要では？

もし必要なら、ログインしていないユーザーがアクセスすることも想定するのだと思いますが、
その場合に、"redirect_to current_user" はうまく働くでしょうか？

2020-09-07 22:41 UTC, fumihisasuzuki commented on app/controllers/users/registrations_controller.rb
> +    if by_admin_user?(params) && resource_class.to_adapter.get(params[:id]).try(:id)
このやり方があるのは知りませんでした。
ポートフォリオでは、if User.find(params[:id]).present? で分岐させてました笑

2020-09-07 22:41 UTC, fumihisasuzuki commented on app/models/user.rb
>    end
.nil?よりも、.blank?の方が汎用性が高かったような気がします。
（nil?だと、falseや""の場合にtrueになってしまいます。）
https://qiita.com/fursich/items/e4be106b2aa639fd3e6a#hogekeyblank

あえてnil?を使用されているならそのままで大丈夫です。

2020-09-07 22:43 UTC, taniryuu commented on app/models/user.rb
>    end
確かにそうですね
テストしてみます

2020-09-07 22:48 UTC, taniryuu commented on app/controllers/application_controller.rb
> +    end
その時はまた別にメソッドを作成した方がいいと思われます。
ここでは主に管理者が他の企業内ユーザーの情報をedit,updateする際に使用しています。
今後削除時も使用する予定です。

authenticate_user!のテストもやってみましたが
なぜか動きませんでしたのであえてここに書きました。

2020-09-07 23:23 UTC, taniryuu commented on app/models/user.rb
>    end
動作的に問題はなさそうでしたが
改めて考えるとここはキツめの設定でnilを使用しようと思います。

nil?だとfalseや""の場合もfalseになるんじゃないですか？
https://qiita.com/aeroastro/items/b58228decb7094af7594

2020-09-07 23:28 UTC, taniryuu commented
確認終わりました。
今朝のマージで発生したコンフリクトを解消しました。
他問題なさそうでしたらマージお願いします。

bootstrapの件はすみません。
少しでも早くbootstrapを導入し他メンバーがbootstrapの使用を意識した開発ができるよう急ぐため
今回含ませていただきました。

2020-09-08 04:21 UTC, fumihisasuzuki commented on app/models/user.rb
>    end
すみません、逆でしたね・・・
nil?だと、falseや""の場合にfalseになってしまいます。
唯一、nilのときだけtrueになるメソッドでしたね。

もしかしたらこういうケースはないのかもしれませんが、User.where(company_id: self.company_id)が、もし""や[]の場合でも、このカスタムメソッドではtrueを返してほしいのではないかな、と思い、blank?を提案しました。nilのときだけtrueを返して、""や[]の場合はfalseで良いなら、現状のままがベストだと思いますが。

2020-09-08 04:31 UTC, fumihisasuzuki requested changes
bootstrapの件は承知しました。お気持ち嬉しいです。
そんな中、追加でコメント申し訳ありませんが、2点追加しましたのでよろしくお願いします。

2020-09-08 04:31 UTC, fumihisasuzuki commented on app/controllers/application_controller.rb
> +    end
理解が追い付いておらず申し訳ありません。
「管理者が他の企業内ユーザーの情報をedit,updateする際に使用」するとはどういうことでしょうか？
「管理者が他の企業内ユーザーの情報をedit,update」できないようにフィルターとして使用するということでしょうか？→そうすると、同じ企業かどうかの判別も必要なような気がします。

あと、「authenticate_user!がなぜか動かない」というのは、コントローラーにbefore_action authenticate_user!を書いていても、ログインしていないユーザーがアクセスできてしまう、ということですか？

2020-09-08 04:31 UTC, fumihisasuzuki commented on app/models/user.rb
>    end
すみません、逆でしたね・・・
nil?だと、falseや""の場合にfalseになってしまいます。
唯一、nilのときだけtrueになるメソッドでしたね。

もしかしたらこういうケースはないのかもしれませんが、User.where(company_id: self.company_id)が、もし""や[]の場合でも、このカスタムメソッドではtrueを返してほしいのではないかと思い、blank?を提案しました。

もし、nilのときだけtrueを返して、""や[]の場合はfalseで良いなら、現状のままがベストだと思いますが。

2020-09-08 04:34 UTC, fumihisasuzuki commented on app/controllers/application_controller.rb
> +    end
だとしたら問題なので、原因究明したい気持ちがあります・・・

2020-09-08 05:53 UTC, taniryuu commented on app/controllers/application_controller.rb
> +    end
このひとつ下にsame_company_idというものを分けて作ってます。
これが企業かどうかの識別をしています。
それもedit,updateにbefore_actionで実行してるので大丈夫だと思いますよ。

user_signed_in?はauthenticate_user!書いてるし要らないかな？
→消したら動かないで戻すと動く???
deviseはほんと裏で何してるかわからないですね

2020-09-08 05:55 UTC, taniryuu commented on app/models/user.rb
>    end
User.whereで""や[]が入っているケース
現状ロジックが壊れている時しか考えられないので大丈夫そうです

2020-09-08 05:56 UTC, taniryuu commented
@fumihisasuzuki 
返信しました！
確認お願いします。

2020-09-08 07:12 UTC, merged