Feature/user delete logic
taniryuu/Rer_Pro pull request #60
Opened 2020-09-09 07:20 UTC by taniryuu

ユーザー削除時のロジックを作成しました(動作テスト済)

削除の流れとして
1. ユーザー一覧から削除ボタンクリックでモーダル表示
2.モーダルのフォームにDeleteと入力後削除できる

controllerには先にDeleteの入力があっているか&&同じ会社のユーザーIDかでif分岐後
ユーザーの持つ案件で完了予定日が空文字の案件を取得使用としてtrueだった場合に削除が実行されます。

確認よろしくお願いします。

2020-09-09 10:21 UTC, fumihisasuzuki requested changes
Deleteと打たないとdestroy出来ない機能の実装、おつかれさまです。
定数の使い方など勉強になりました。
2点、コメントさせていただきました。よろしくお願い致します。

2020-09-09 10:21 UTC, fumihisasuzuki commented on app/controllers/users_controller.rb
> +        flash[:success] = "成功しました" if @user.destroy
@user.destroyがfalseを返す場合ってあるのでしょうか？
falseを返すことがあるなら、else分岐が必要と考えます。
falseを返すことがないなら、ifは使わずに下記で良いのではないでしょうか。
```
@user.destroy
flash[:success] = "成功しました"
```

2020-09-09 10:21 UTC, fumihisasuzuki commented on app/controllers/users_controller.rb
> +      flash[:danger] = "正しく入力してください"
"正しく入力してください"だけだと、Userは「何をどうすればよいの？」となる可能性があります。
また、他の会社のユーザーを削除しようとした際にこちらに飛んだ場合も想定する必要があると思います。
多少長くなっても良いので、37行目のように、起きたエラーの内容と、具体的な次の行動の指示を書くのはいかがでしょうか？

2020-09-09 12:36 UTC, taniryuu commented on app/controllers/users_controller.rb
> +        flash[:success] = "成功しました" if @user.destroy
それもそうですね。
そのようにします。

2020-09-09 12:43 UTC, taniryuu commented on app/controllers/users_controller.rb
> +      flash[:danger] = "正しく入力してください"
ヘルパーのsame_company_id_judge(@user)と書いたのはただの保険のような物でviewからはこのヘルパーはtrueを絶対返すようになってますが...攻撃的なユーザーがいた場合の処理になってますが
上のDeleteと正しく入力してくださいとあえて書く必要ありますかね？
具体的指示はフォームラベルにDeleteと入力してくださいと書いてますが

ここはリファクタリング案件ですがDeleteと入力した時だけbtnクラスを押せるように設計する予定です。

2020-09-09 12:56 UTC, taniryuu commented on app/controllers/users_controller.rb
> +      flash[:danger] = "正しく入力してください"
じっくり考えてもやはりここはこれで良いと思いますよ。
指示にくどく感じそうです。

viewのフォームもみてください。

2020-09-09 12:58 UTC, taniryuu commented
@fumihisasuzuki 
修正行いました。
コメントにも返信したので確認お願いします。

2020-09-10 00:23 UTC, fumihisasuzuki commented on app/controllers/users_controller.rb
> +      flash[:danger] = "正しく入力してください"
もしかしたら、谷口さんのおっしゃる通りくどくは感じるかもしれません。端的に表示できた方がスマートですし。

一方、私の考えは、多少くどかったりスマートでなかったりしても、情報が改めて表示される方がユーザーフレンドリーと思っています。ので、そうですね、私が書くとしたら
「キーワードが間違っています。"Delete"と正しく入力されているかご確認下さい。」
とかですかね。
(placeholderは、ユーザーが文字を打つと消えてしまうので、改めて表示することに意義はあると考えます。)

ただ、これは考え方の問題と思いますので、PMが現状がベストと判断されるならそれはそれで構いません。私もなるべくその方針に合わせます。

2020-09-10 00:29 UTC, fumihisasuzuki commented on app/controllers/users_controller.rb
> +      flash[:danger] = "正しく入力してください"
また、保険でも、分岐を設定する以上は両方の道に行くことを想定して実装する方が、後々のバグ対応が楽なのではという考えから、コメント致しました。
現状、万が一保険の方でひっかかった場合、デバッカーをはさんであれこれ値を調べないと原因が特定できませんが、if文で分岐を分けておけば、何でひっかかったのかエラーメッセージを見るだけで判断できるからです。

ただ、これに関しても、PMが問題なしと判断されるのでしたら、それで構いません。私も経験がないので、絶対こうだ、とまでは言い切れません。

2020-09-10 00:36 UTC, merged