Add canceled list
taniryuu/Rer_Pro pull request #64
Opened 2020-09-12 15:45 UTC by ruffini47

<主な変更点>
・中止リストを作成しました。
・ToDoリストの中止ボタンを押すことで中止リストに追加。
・中止リストの復活ボタンを押すことによりToDoリストに復活。その際モーダルで「完了予定日」カラムの手動入力を要求。
<細かい変更点>
・済リストの名前を詳細ページへリンクできるようにする。
・済リストを完了予定日でソート
・詳細編集の画面に削除ボタンを設置。
・担当者のみ編集可能、削除可能。
・完了日に未来の日付を入れることはtaskモデルのvalidationで禁止。
・完了予定日、完了日に過去の日付を入れようとするとcontrollerからアラートを出す。
以上です。

2020-09-12 22:53 UTC, fumihisasuzuki requested changes
気づきコメントしました。
不明点あれば返信いただければ幸いです。

2020-09-12 22:53 UTC, fumihisasuzuki commented on app/controllers/tasks_controller.rb
> +    end
ここでアラートをフラッシュに挿入すると、UXとしては、タスクの新規作成が完了したあとに、このアラートメッセージが表示されることにならないでしょうか？
submitを送ったあとに、削除するときによく記載する「data: { confirm: hogehoge} 」のような形で確認メッセージを出して、OKならそのままcreate, キャンセルならredirectするように実装できないでしょうか？

ここはSTEPやLEADでも必要なロジックなので、私もやり方を調査してみます。

2020-09-12 22:53 UTC, fumihisasuzuki commented on app/controllers/tasks_controller.rb
> +        end
１．blank?の否定はpresent? ですので、@task.completed_date.present?で全く同じ意味になります。左記のとおりリファクタリングする方が可読性が向上すると考えます。

２．また、day_is_older_than_nowのメソッドの方に、存在を確認して変数がblankならfalseを返すように実装する方がDRYです。このメソッドを使うときは空だと必ずエラーを吐くわけですから、このようなケースでは、常に存在証明とセットで使うことになります。だったら、予め一緒にしておく方が良いね、という考え方です。

３．上記２をすれば、よりコードがシンプルになり、今回のifはネストしなくてよくなると考えます。（47行目と52行目もDRYにできます。）言い換えると、３つのケースを
```
if A & B
elsif A
elsif B
end
```
の形式で分岐するだけで済むと考えます。

2020-09-12 22:53 UTC, fumihisasuzuki commented on app/controllers/tasks_controller.rb
> +    @deleted_tasks_array = @step.tasks.where(status: "completed").order(:scheduled_complete_date)
ここも配列名を見直し願います。

2020-09-12 22:53 UTC, fumihisasuzuki commented on app/controllers/tasks_controller.rb
> +    end
下記２つの組み合わせで、よりDryなコードにリファクタリングできないでしょうか？
（現状、比較する日付を３回ずつ呼び出していますので・・・）

１．文字列からparseを使ってDateオブジェクトに変換：
https://qiita.com/prgseek/items/c0fc2ffc8e1736348486#-date%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E7%94%9F%E6%88%90

２．Dateオブジェクトの大小比較
https://qiita.com/prgseek/items/c0fc2ffc8e1736348486#-date%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%A4%A7%E5%B0%8F%E6%AF%94%E8%BC%83

2020-09-12 22:53 UTC, fumihisasuzuki commented on app/models/task.rb
> +                                                                                         Date.current.year * 10_000 + Date.current.month * 100 + Date.current.day
＜再掲＞
下記２つの組み合わせで、よりDryなコードにリファクタリングできないでしょうか？
（現状、比較する日付を３回ずつ呼び出していますので・・・）

１．文字列からparseを使ってDateオブジェクトに変換：
https://qiita.com/prgseek/items/c0fc2ffc8e1736348486#-date%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E7%94%9F%E6%88%90

２．Dateオブジェクトの大小比較
https://qiita.com/prgseek/items/c0fc2ffc8e1736348486#-date%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%A4%A7%E5%B0%8F%E6%AF%94%E8%BC%83

2020-09-12 22:54 UTC, taniryuu requested changes
確認しました！
また説明をお願いしている部分がありますので
よろしくお願いします。

2020-09-12 22:54 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +    if day_is_older_than_now(@task.scheduled_complete_date)
このifはモデルに書けそうですね。
次回以降挑戦してみてください。

2020-09-12 22:54 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +          if !@task.completed_date.blank? && day_is_older_than_now(@task.completed_date)
!を外してpresent?でも動きそうですよ

参考:https://qiita.com/aeroastro/items/b58228decb7094af7594

2020-09-12 22:54 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +      @lead = Lead.find(@step.lead_id)
128,129行目は134,135や140,141行目と同じですね。
DRYということでまとめても良いとおもいます。

2020-09-12 22:54 UTC, taniryuu commented on app/assets/stylesheets/custom.scss
> +.modal-dialog-center {
tasks.scssと分けた理由ってあります？

2020-09-12 22:54 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +    def day_is_older_than_now(day)
このメソッドについてまた教えていただいてもよろしいですか？

2020-09-12 22:54 UTC, taniryuu commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
app/views/tasks/_edit_revive_from_canceled_list.html.erbのjsはこのように切り分けることができるんですね。
知らなかったです。

2020-09-13 02:41 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
>    end
完了リスト、中止リストも完了予定日しか表示していなかったので完了予定日でソートしていましたが、完了リストでは完了日表示、完了日順、中止リストでは中止日を表示、中止日順に変更したいと思います。

2020-09-13 03:17 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +        end
day_id_older_than_nowに存在確認を含めるように変更しました。それに伴いifをネストしないように書き直しました。

2020-09-13 03:18 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    @deleted_tasks_array = @step.tasks.where(status: "completed").order(:scheduled_complete_date)
配列名@deleted_tasks_arrayを@completed_tasks_arrayに書き直しました。

2020-09-13 03:26 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    end
Dateクラスには日付を便利に使える方法が用意されているのですね。リファクタリングしました。

2020-09-13 03:31 UTC, ruffini47 commented on app/models/task.rb
> +                                                                                         Date.current.year * 10_000 + Date.current.month * 100 + Date.current.day
同じくリファクタリングしました。

2020-09-13 03:32 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    if day_is_older_than_now(@task.scheduled_complete_date)
次回以降挑戦します。

2020-09-13 03:35 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +          if !@task.completed_date.blank? && day_is_older_than_now(@task.completed_date)
!..blank?は...present?と同じですね。ここでは鈴木（文）さんの指摘に従い、存在確認をday_is_older_than_nowメソッドの中に含めました。

2020-09-13 03:40 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    def day_is_older_than_now(day)
このメソッドはString型を数値に直してから比較しましたが、DRYの観点上思わしくなかったので、鈴木（文）さんの指摘に従い、Date.parse(day)でdayをDateオブジェクトに変換してからDate.currentと比較するように修正しました。

2020-09-13 03:41 UTC, ruffini47 commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
これも勤怠システムチュートリアルに書いてあった通りのコードです。

2020-09-13 04:27 UTC, ruffini47 commented on app/assets/stylesheets/custom.scss
> +.modal-dialog-center {
特に理由はありません。勤怠システムチュートリアルに書いてあった通りにしました。tasks.scssに書いてもいいのですね。tasks.scssに移動しておきます。

2020-09-13 04:31 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +      @lead = Lead.find(@step.lead_id)
set_task,set_step,set_step_in_add_delete_listの対象のメソッドがそれぞれ違うのでまとめることはできなさそうです。

2020-09-13 05:02 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +      @lead = Lead.find(@step.lead_id)
set_task,　set_step,　set_step_in_add_delete_list

これらを一つにまとめるのは無理ですが
@lead = Lead.find(@step.lead_id)
@user = User.find(@lead.user_id)
をset_task,set_step,set_step_in_add_delete_listを動かしてるアクションに対してbefore_actionすると動きません？
ややこしく感じるならこのままで大丈夫ですよ

2020-09-13 05:06 UTC, taniryuu commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
ちなみにどの辺りの章ですか？
復習しますので教えてください。

2020-09-13 05:07 UTC, fumihisasuzuki commented
コメント見ました、ご返信ありがとうございます。
修正後のコードが見れないのですが、まだプッシュされていませんか？

2020-09-13 05:22 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    end
ここの「data: { confirm: hogehoge}」のような形の確認メッセージの出し方がよく分かりませんでした。

2020-09-13 05:33 UTC, ruffini47 commented
完了予定日、完了日に過去の日付を入れようとしたとき「data: { confirm: hogehoge}」のような形の確認メッセージを出そうと思いましたが、そのようなメッセージの出し方が良く分かりませんでした。
それ以外の修正は対応しました。

2020-09-13 05:39 UTC, ruffini47 commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
「勤怠システムチュートリアルの第9章9.3.1モーダルウィンドウを表示しよう」にあります。

2020-09-13 05:40 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +      @lead = Lead.find(@step.lead_id)
今は時間が無いので落ち着いたら考え直してみます。

2020-09-13 06:28 UTC, fumihisasuzuki commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
ただ、勤怠チュートリアルはbootstrap3で、今回はbootstrap4を使用しておりますので、多少違いが出てくる可能性があります。今回、動いているならこのままで大丈夫と考えていますが、頭の片隅に置いておいていただけると、今後上記違いが表出してきたときに役立つと思います。

2020-09-13 06:40 UTC, fumihisasuzuki reviewed
ありがとうございます。
コメント追加しました。
保存するときにアラートを出すロジックも、もし出来ましたら教えていただけると幸いです。

2020-09-13 06:40 UTC, fumihisasuzuki commented on app/controllers/tasks_controller.rb
> +      end
三項演算子を使って、下記の通りリファクタリング出来ないでしょうか？
`return day.blank? ? false : (Date.parse(day) < Date.current)`
returnや()は不要かもしれません。条件を返すもので使ったことがあるわけではないので、出来なかったらごめんなさい・・・

2020-09-13 08:27 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +      end
三項演算子を使って書き直しました。returnや()は不要で正しく動きました。

2020-09-13 08:32 UTC, ruffini47 commented
三項演算子を使った修正後、プッシュしました。

2020-09-13 08:52 UTC, taniryuu commented on app/views/tasks/edit_revive_from_canceled_list.js.erb
> +$("#edit-revive-from-canceled-list").html("<%= escape_javascript(render 'edit_revive_from_canceled_list') %>");
ありがとうございます。
覚えてない理由もなんとなくわかりました。
今なら全部わかります。
説明も最低限ですね。

2020-09-13 08:57 UTC, taniryuu commented
確認しました！
修正＆コメントありがとうございます。
私からは特に問題なさそうでした。

@fumihisasuzuki 
確認して問題なければマージしようと思います。

2020-09-14 03:27 UTC, fumihisasuzuki commented
@taniryuu 
返信遅れまして申し訳ございません！
問題ないと思います。マージお願い致します。

次回以降、基本的に谷口さんが問題なしと判断されたらマージしていただいて構いません。
（根本的なものやアプリ全体に影響が及ぶものは別ですが、ほとんどのコメントは後から修正できるものが多いかと思いますので。）
もしも追加コメントがある場合は、別の機会か、trelloのissueカードにて対応致します。
以上、よろしくお願い申し上げます。

2020-09-14 04:56 UTC, taniryuu commented
@fumihisasuzuki 
了解です！
マージします

2020-09-14 04:56 UTC, merged