タスクコントロールの操作後のイベント実装
taniryuu/Rer_Pro pull request #67
Opened 2020-09-15 14:53 UTC by ruffini47

<主な変更点>
・基本設計書の５．タスクコントロールの操作後のイベント「進捗新規作成時イベント」、「進捗完了時イベント」、「完了済進捗編集時イベント」の実装。
<細かい変更点>
・タスク更新でstatusを完了にしたとき、完了日が空白なら完了日を本日にする。
・タスク更新でstatusを中止にしたとき、中止日が空白なら中止日を本日にする。
・消し込みボタンで消し込みするとき、中止ボタンで中止するとき、復活ボタンで復活するとき、タスク達成率を更新する。

2020-09-16 01:11 UTC, taniryuu requested changes
確認しました！
複雑なロジックの作成お疲れ様です。
故に少々読みにくい部分や説明が欲しい部分がありましたのでコメント残しました。
確認よろしくお願いします。

2020-09-16 01:11 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +    def check_status_and_get_url
ここのメソッドも何をしているとコメントに残してください

2020-09-16 10:54 UTC, ruffini47 commented on app/assets/stylesheets/tasks.scss
> +
これはモーダル用に書いたコードなので必要無いです。削除しておきます。

2020-09-16 10:54 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +                                          edit_check_status_2 update_check_status_2 edit_check_status_3 update_check_status_3)
あまり長くなると%記法は逆に見にくくなるんですね。変更しておきます。

2020-09-16 11:06 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    case params[:status_3]
バリデーションを回避したい理由はありません。update_attributesはupdateのエイリアスなんですね。updateを使ってみます。

2020-09-16 11:21 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +    def check_status_and_get_url
後から来る人にもわかるようにコメントを入れました。

2020-09-16 11:54 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +  def edit_check_status_1
後からこのチームに参画した人でもわかりやすいように、
それぞれのメソッドにコメントを追加しました。

2020-09-16 12:02 UTC, ruffini47 commented on app/views/tasks/edit_check_status_1.html.erb
> +  <% end %>
1,2,3それぞれ、修正しました。

2020-09-16 13:09 UTC, ruffini47 commented on app/controllers/tasks_controller.rb
> +      if day_is_older_than_now(@task.scheduled_complete_date) && day_is_older_than_now(@task.completed_date)
モデルでメソッドif_date_blank_then_todayを定義して使ってみました。

2020-09-16 14:43 UTC, ruffini47 commented
プルリク修正対応し、プッシュしました。
上記の指摘変更以外に、復活モーダルが動作しなくなりましたので、復活ボタン押下後も普通のrails画面に遷移するように
変更しました。その他、より明確にするため、app/views/tasks/edit_check_status_1.html.erbの文言を”現在の進捗を継続する”－＞”現在の進捗を「進捗中」とする”、app/views/tasks/edit_check_status_2.html.erbの文言を"現在の進捗を完了する”－＞”現在の進捗を「完了」とする”のように変更しました。

2020-09-16 22:00 UTC, fumihisasuzuki commented
すぐにコメントできず申し訳ありません。
status_1, status_2, status_3というネーミングは可読性が著しく低いと思うのですが・・・皆さんはどのように考えるでしょうか？
何かに対応した意味のある数字なら使っても良いと思うのですが、この場合は３種類のメソッドに付番しただけと思いますので、修正いただけるとありがたいです。（1,2,3とかa,b,cとかいう付番は、サンプルコードでしか見たことがありません。）
例えば、
１はcontinue_or_destroy_step
２はcomplete_or_continue_step
３はchange_status_or_complete_task
などはいかがでしょうか。（上記に、必要に応じてeditやcheckなどを頭につけて調整してみてください。）

2020-09-16 23:31 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +    def check_status_and_get_url
なるほどありがとうございます。かなりわかりやすいです。

これは修正依頼とは違いますが
@step.tasks.where(status: "not_yet").count == 0
は@step.tasksにstatusが"not_yet"になっている物を全件取得させ件数が0の時って意味ですがこう書き換えることもできるはずです。

@step.tasks.find_by(status: "not_yet").nil?
大きな違いはfind_byで最初に検索にかかったデータを取得してるのでもしstatus: "not_yet"のデータがあったのなら@step.tasksの検索は取得時点で終了(速度向上)
1以上の場合はpresent?にするとかですね。
可読性が良い方を選択してみて下さい。

2020-09-16 23:32 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +  def edit_check_status_1
ありがとうございます。

2020-09-16 23:41 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +      if day_is_older_than_now(@task.scheduled_complete_date) && day_is_older_than_now(@task.completed_date)
失礼しました。
気づきませんでした。

2020-09-17 00:01 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +                                          edit_check_status_2 update_check_status_2 edit_check_status_3 update_check_status_3)
ありがとうございます。
_が入ると区切りがぱっと見でわかりにくくなりますね。
勉強になります。

2020-09-17 00:08 UTC, taniryuu commented on app/controllers/tasks_controller.rb
> +    case params[:status_3]
わかりました。
実際にテストしてみてまずそうならissueにあげます。

2020-09-17 00:12 UTC, taniryuu commented on app/views/tasks/edit_check_status_1.html.erb
> +  <% end %>
ありがとうございます

2020-09-17 00:29 UTC, taniryuu commented
説明と修正ありがとうございます。
status1,2,3って何？ってなってそこに脳の処理を使ってしまうのであまりよくないです。

修正箇所と確認しないといけないファイルが多くなりそうなので別のプルリクで上げて下さい。
今回はこれでマージします。

macだとコマンド+dで同じコードは複数選択して同時に編集できるのですがwindowsでもできるはずですので
調べてみて下さい。効率が上がります。

2020-09-17 00:29 UTC, merged

2020-09-17 14:39 UTC, ruffini47 commented
いいえ、コメントして頂けるだけでありがたいです。
鈴木（文）さんの提案通り
status_1, status_2, status_3はcontinue_or_destroy_step、complete_or_continue_step、change_status_or_complete_taskに
リネームしました。詳しくはプルリクhttps://github.com/taniryuu/Rer_Pro/pull/71
に上げました。