Cancel step
taniryuu/Rer_Pro pull request #73
Opened 2020-09-19 09:35 UTC by fumihisasuzuki

下記の実装を行いました。（基本設計書4-2「進捗コントロール」19-21行目に該当）
１．completeアクションの作成（同じ記述が２か所にあったためリファクタリング）
２．進捗の保留処理（進捗中→保留）
　　その過程で、canceled_dateカラムを追加。（したがって、pull後migrate必須）
３．進捗の再開処理（保留/完了→進捗中）
４．check_status_completed_or_notメソッドの作成

１はただのリファクタリングです。
２が、当初今回のプルリクのメインだったのですが、行きがあるなら帰りもないと、ということで３を実装する際に、４が必要になったためこのような変更内容となりました。

４は、completed_data, status, rateが矛盾しないように整えるメソッドです。
例えば、rateは100%なのにstatusが進捗中、だとか、「未」の進捗があるのにstatusが「完了」のまま、だとか、そういった状態になったときに、どちらかに揃えています。（どんな挙動をするかは、実際に触ってみてほしいです。余裕があれば、お願いします。ユーザー視点で、期待する挙動にギャップがあったら、ご指摘をお願いします。）

2020-09-19 12:04 UTC, taniryuu requested changes
確認しました！
check_status_completed_or_notメソッドはマージされてから確認するようタスクに入れておきます。

気になったところにコメントを残してますので確認と、コンフリクトの修正もお願いします。

2020-09-19 12:47 UTC, fumihisasuzuki commented
プルしてなかった分が変更として反映されてしまっているようです。申し訳ありません。
改行も追加しておきます。（本日、改行の話もありました・・・早速やってしまい情けないです）

2020-09-19 12:53 UTC, fumihisasuzuki commented
プルしてコンフリクト解消し、２件、改行を追加いたしました。

ご確認をお願い致します。

2020-09-19 13:51 UTC, taniryuu commented
確認しました！
エラー消えてますね。ありがとうございます。

画面上だと何故か#72のプルリクの差分が今回のプルリクの差分と混ざってる表示になってますので
念の為松本さんにもレビューを頼んでおきます。
レビューがokならマージします。

2020-09-19 20:20 UTC, fumihisasuzuki commented on config/routes.rb
> +  resources :companies do
今回ルーティングは、33行目の
        patch 'complete/:completed_id' => 'steps/step_statuses#complete', as: :complete
を追加しただけで他はいじっていないんですよね・・・

最新のルーティングを送っていただけたら、それに編集することはできます。
あるいは、ルーティングだけgitで戻ってから上記追加してもいいかなと思います。

2020-09-20 04:51 UTC, ruffini47 commented
遅くなってすみません。
私のほうではレビュー大丈夫です。
マージをよろしくお願いします。

2020-09-20 04:55 UTC, taniryuu commented
@ruffini47 
確認ありがとうございます。
わかりました。マージします。

2020-09-20 04:55 UTC, merged