Company model設定
taniryuu/Rer_Pro pull request #8
Opened 2020-08-18 08:36 UTC by taniryuu

modelにバリデーション、
migrateファイルにdefault値設定、
seed.rbに管理者サイドのアカウント作成文を追加しました。

seed.rbの下にコメントアウトしているcreate文がありますが
ペルソナに指定している会社を作成するため、一時的にコメントアウトにしています。

確認お願いします

2020-08-18 21:47 UTC, fumihisasuzuki requested changes
２点コメントしました！
修正お願いできますか？
自分の担当のプルリクがまだなので恐縮ですが・・・笑

2020-08-18 21:47 UTC, fumihisasuzuki commented on app/models/company.rb
> +                     numericality: { greater_than_or_equal_to: 0,
statusは、enumを使うことになっていたと思います。単に数字として扱うよりも、後々のバグの可能性が減るので、enumにしたいと私は考えます。
記事は、例えばこちらとかを参照してみてください。
https://web-camp.io/magazine/archives/16862
日本語名は、ja.ymlファイルで設定をお願いします。

私の担当になっているLeadやStepも上記参考に実装する予定です。

2020-08-18 21:47 UTC, fumihisasuzuki commented on db/seeds.rb
> +#   name: "システム管理",
紛らわしいので、「ペルソナの会社」などと、わかるような表現にしていただけると助かります。プルリクの文章を読むまで「？？」となってしまいましたので・・・
合わせて、adminもfalseにしておいてくださるとわかりやすいです。

2020-08-18 22:32 UTC, taniryuu commented on app/models/company.rb
> +                     numericality: { greater_than_or_equal_to: 0,
gemファイルのマージがまだだったのでこの形でプルリクを上げてました。
gemのrails-i18nは入れてませんでしたのでまた後ほど入れておきます

2020-08-18 22:41 UTC, taniryuu commented on db/seeds.rb
> +#   name: "システム管理",
修正しました

2020-08-18 22:45 UTC, taniryuu commented on app/models/company.rb
> +                     numericality: { greater_than_or_equal_to: 0,
記事を読むとrails-i18nがなくても対応できるんですね。

2020-08-19 20:46 UTC, fumihisasuzuki commented on db/seeds.rb
> +#   name: "システム管理",
ありがとうございます！

2020-08-19 20:49 UTC, fumihisasuzuki commented on app/models/company.rb
> +                     numericality: { greater_than_or_equal_to: 0,
そうみたいですね。gemのrails-i18nは別のプルリクにしていただいて大丈夫そうです。よろしくお願い致します。

2020-08-20 23:01 UTC, closed without merging