Revise lead index3(Final)
taniryuu/Rer_Pro pull request #80
Opened 2020-09-27 05:24 UTC by fumihisasuzuki

## やったこと
* 案件一覧で、各案件にホバーすると追加情報を表示。（CSSでツールチップ使用）
* 案件一覧で、現在ソートしている列を強調。
* 案件のstatusに応じた進捗があるように、Stepのバリデーションを修正。
## やらないこと
* 色や大きさなど、気に入らない箇所は多数ありますが、そのあたりの調整は後回しとしています。
## できるようになること(ユーザ目線)
* 案件一覧で、各案件にホバーすると追加情報を表示。
## できなくなること(ユーザ目線)
* なし
## 動作確認
* ホバーすると、各案件の追加情報が表示されることを確認しました。
## その他
* なし

2020-09-27 07:45 UTC, taniryuu requested changes
確認してコメント残しました！
#79 のプルリクってcloseしてもよろしいですか？

2020-09-27 07:45 UTC, taniryuu commented on config/locales/kaminari_ja.yml
> +
改行入ってるように見えるのに？？？
不思議ですね

2020-09-27 07:45 UTC, taniryuu commented on app/assets/stylesheets/leads.scss
> +}
scssのTabの設定が4になってるかもですね。
半角4マスずつにインデントなってます

2020-09-27 09:55 UTC, fumihisasuzuki commented on app/assets/stylesheets/leads.scss
> +}
設定は2なんですが、たまにこの現象起こるんですよね・・・スペースを駆使して2マス分に修正してみました。

2020-09-27 09:56 UTC, fumihisasuzuki commented on config/locales/kaminari_ja.yml
> +
改行＋タブだったので、改行のみにしてみました。

2020-09-27 10:01 UTC, fumihisasuzuki commented
コメント2件、ありがとうございます。修正致しました。

前のプルリクマージ前に別のプルリク出すと、どちらの差分も含まれるんですね（developブランチとの差分がプルリクとして上がると言うことですね。）
失礼致しました。クローズしておきます。

2020-09-27 10:07 UTC, taniryuu approved these changes
確認しました！
修正ありがとうございます。
これで大丈夫かと思います。

2020-09-27 10:32 UTC, ruffini47 commented on app/views/kaminari/_page.html.erb
> +    <%= content_tag :a, page, data: { remote: remote }, rel: page.rel, class: 'page-link' %>
ここではなぜ、直のHTMLでなくcontent_tag :aを使っているのですか？

2020-09-27 10:58 UTC, fumihisasuzuki commented on app/views/kaminari/_page.html.erb
> +    <%= content_tag :a, page, data: { remote: remote }, rel: page.rel, class: 'page-link' %>
kaminariにbootstrapを適用するために
`rails g kaminari:views bootstrap4`
を実行した際に自動生成されたものですので、はっきりとしたことはわかりません・・・

ご参考
https://qiita.com/hiro266/items/809a26fed8a962851417

2020-09-27 11:05 UTC, ruffini47 commented on app/models/step.rb
> +      errors.add(:status, ":凍結中の案件には、凍結中の進捗が必要です。") unless self.status = "inactive"
error.addの後のunlessはなぜ付けているのですか？

2020-09-27 11:13 UTC, ruffini47 approved these changes
コメントが遅くなってしまいました。
確認しました。

2020-09-27 14:59 UTC, ruffini47 commented on app/views/leads/leads/index.html.erb
> +                <%= render "index_sort", mark: " ▲ ", sort: "user_id desc" %>
renderでは既定のオプションだけでなく、自作の変数(:mark,:sort)も渡せるのですか？

2020-09-27 22:33 UTC, fumihisasuzuki commented on app/models/step.rb
> +      errors.add(:status, ":凍結中の案件には、凍結中の進捗が必要です。") unless self.status = "inactive"
例えば、"in_progress"の状態のLeadレコードがあって、そのレコードにはStepレコードがひとつもない状態のときに、Stepレコードをcreateするとします。
その際に、もちろんここのバリデーションを通るのですが、この時点ではまだStepレコードはcreateされていないため、
lead.steps.find_by(status: "in_progress").blank?
が必ずtrueになってしまい、エラーとなってしまいます。
しかし、実用上は、新しくcreateしようとしているStepモデルのstatusが"in_progress"であれば問題ありません。

したがって、self.statusが"in_progress"の場合にエラーにならないよう、条件式を追加しています。

2020-09-27 22:41 UTC, fumihisasuzuki commented on app/models/step.rb
> +      errors.add(:status, ":凍結中の案件には、凍結中の進捗が必要です。") unless self.status = "inactive"
今気づいたのですが、unless以下が、等式（==）ではなくて代入（=）になっていますね・・・これでは、必ずtrueになるので必ずバリデーションが通ってしまうことになっておりました。
ご指摘いただいて気づけました。修正しましたのでご確認ください。

2020-09-27 22:45 UTC, fumihisasuzuki commented on app/views/leads/leads/index.html.erb
> +                <%= render "index_sort", mark: " ▲ ", sort: "user_id desc" %>
はい、渡せます。「rails render 変数」などでググってみてください。
エラーメッセージの部分テンプレートでも、実は既に利用していますよ。

2020-09-27 22:51 UTC, fumihisasuzuki commented
いただいていたコメントに3件、回答致しました。1件は誤記に気づきましたので修正致しました。

2020-09-28 01:47 UTC, taniryuu commented
わかりました！
マージします。

2020-09-28 01:47 UTC, merged