Accordion display 2
taniryuu/Rer_Pro pull request #85
Opened 2020-10-01 15:12 UTC by ruffini47

## やったこと
タスクの済リストと中止リストをアコーディオン表示にした。日付の設定にstrftimeの替わりにl メソッドを用いて書き換えた。
## やらないこと
＃～未マージの為cancel stepメソッドは使用していません。
## できるようになること(ユーザ目線)
タスクの済リストと中止リストをアコーディオンで表示できる。
## できなくなること(ユーザ目線)
タスクの済リストと中止リストのクリックなしの一覧表示はできなくなった。
## 動作確認
db/seed.rbファイルによるrails seed。
## その他
l メソッドのデフォルトの日付フォーマットは"%Y/%m/%d"ですが、フォームから日付を入力する場合"%Y-%m-%d"になりますので、lメソッドの方もこれに合わせるため、lメソッドでformat: :standardオプションを付けて、フォーマットを"%Y-%m-%d"に統一しました。

2020-10-01 23:01 UTC, fumihisasuzuki requested changes
コメントアウトの削除依頼が3件、
日付の表示に関するコメントが2件、
今後のリファクタリング提案に関してが1件、
計6件コメント致しました。ご確認をお願い致します。

2020-10-01 23:53 UTC, taniryuu approved these changes
確認しました！
私からは既にコメントもありますので特にありません。
修正が済んだらマージしてもOKです。

2020-10-02 11:42 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      # flash[:danger] = "#{step.name}の中止処理に失敗しました。システム管理者にご連絡ください。"
予備で残しておいたコメントですね。削除しておきます。

2020-10-02 11:44 UTC, ruffini47 commented on app/controllers/leads/steps_statuses_controller.rb
> +#    redirect_to @step
同様に、削除しておきます。

2020-10-02 11:52 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +      redirect_to check_status_and_get_url
「進捗を進捗中にする」メソッドの作成お願いします。「進捗を進捗中にする」を共通メソッドにするとすると、同様に「進捗を未にする」のほうは共通メソッドにしなくて良いのでしょうか？

2020-10-02 11:54 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +      #redirect_to check_status_and_get_url
ここも同様に削除しておきます。

2020-10-02 13:13 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +          deleted_task.update_attribute(:completed_date, (l Date.current, format: :standard))
このプルリクを上げた時点で、viewの表示形式を変えればいいことに気付いていませんでした。（フォームのデフォルトの形式が"%Y-%m-%d"になっていたので、format: :standard形式にしていました。）viewで自由に日付フォーマットを変えられれば、DBやDate.currentを設定するときの形式は何でも良いのでformat: :standardオプションは消すことにします。その上でview上の形式format: :shortdateオプションでを〇月△日のようにしました。

2020-10-02 13:15 UTC, ruffini47 commented on db/seeds.rb
> +    scheduled_complete_date: (I18n.l Date.current + 3, format: :standard),
DBには年まで入っていたほうが良いということですのでlメソッドはこのまま使うことにし、format: :standardオプションはあっても無くても同じなので消すことにします。

2020-10-02 13:31 UTC, ruffini47 commented
コメント確認しました。
不要なコメントを削除し、日付の入力形式をオプションなしのl メソッドで、日付の表示形式をformat: :shortdateオプション付きのl メソッドの形式に変更してプッシュしました。
ご確認下さい。

2020-10-02 14:37 UTC, fumihisasuzuki approved these changes
修正ありがとうございます。
lメソッドだけでも動くというのも初めて知りました。
PMOK出ているのでマージ致します。

2020-10-02 14:37 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +      redirect_to check_status_and_get_url
「進捗を進捗中にする」メソッドは
https://github.com/taniryuu/Rer_Pro/pull/86
にて作成したので、ご確認をお願い致します。

「進捗を未にする」操作は、現状おそらくここでしか出てこないので、メソッドにはしなくて良いと考えていましたが・・・必要になったらまたその時考えるのでいかがですか？
原則、「将来必要になるかもしれない（けど現状不要な）機能」は必要になったときに追加する方針が良いと、個人的には考えています（結果不要だった際に、保守性が落ちるため）。将来ほぼ確実に必要な機能なら現時点で実装してしまってよいとは思いますが。

2020-10-02 14:37 UTC, merged

2020-10-02 14:53 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +      redirect_to check_status_and_get_url
「進捗を未にする」操作が他で出ないなら、そのままでいいですね。「進捗を進捗中にする」メソッドは
＃８６
で確認しました。ありがとうございます。