Use render partial 2
taniryuu/Rer_Pro pull request #89
Opened 2020-10-04 06:38 UTC by ruffini47

## やったこと
・app/views/leads/steps/show.html.erbのタスク部分をパーシャル化してrender partialで読み込むようにした。
・taskコントローラでdesplay_stepメソッドを使用した。
・app/models/taks.rbでlメソッドをI18n.lメソッドに変更
## やらないこと
・taskコントローラでstart_stepメソッド、complete_stepメソッドは仕様が合わないため使用しなかった。
## できるようになること(ユーザ目線)
特にありません。リファクタリングだけです。
## できなくなること(ユーザ目線)
特にありません。
## 動作確認
TaskのCRUD操作。削除チェックボックス、中止ボタン、復活ボタンが正しく機能すること。
## その他
start_stepメソッドは元来フォームから使用する仕様になっているのでparams[:step][:scheduled_complete_date]などがないので使用できませんでした。
complete_stepメソッドは完了日を完了タスクのもっとも遅い完了日にする必要があるため、仕様が合わないため使用しませんでした。

2020-10-04 13:47 UTC, fumihisasuzuki requested changes
complete_stepメソッドについてと、start_stepメソッドについて、1件ずつコメントしました。
もしかしたらzoomで話す方が早いかもしれませんが・・・

あと、`.where(status: "～")`としているところは、ぜひscopeを、
条件式で` .status == "～"`としているところは、ぜひモデルファイルに書いたメソッドをご活用ください。（このプルリクでなくても構いませんが）

2020-10-04 13:47 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +      #start_step(@lead, @step)
進捗を「進捗中」にする処理が、
　１．142行目～153行目
　２．175行目～185行目
　３．207行目～211行目（ここ）
の3か所にあるかと思いますが、ここにstart_stepメソッドがそのまま適用できなかったということでしょうか？

＜１のケース＞
ここでは、new_task.save成功後に、start_stepメソッドを挿入することでいかがでしょうか？どんな問題が生じますか？
また、少しだけ話題が逸れますが、
`flash[:danger] = "新しいタスクの追加に失敗しました"`
のメッセージを見たユーザーは次にどうしたら良いのでしょうか、おそらく、どうしようもありません。
バリデーションにひっかかりようのないnew_task.saveでしたら、最初から`create!`してしまっても良いのかな、と思いました。

＜２のケース＞
ここは１のケースと全く同じ処理をしているのではないでしょうか？？
メソッド化しても良いかもしれませんね。

＜３のケース＞
ここは、そのまま`start_step(@lead, @step)`に置き換えられるような気がしてしまうのですが、どのような不具合があったのでしょうか？

以上、よろしくお願い致します。

2020-10-04 13:47 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
>        update_steps_rate(@lead)
進捗の完了処理は、それ単体だと他のデータと矛盾を起こす可能性があります。
（次に着手する進捗がなければ、既存の進捗のいずれかを「進捗中」にするか、「進捗中」の進捗を新しくつくる必要がありますし、最後の進捗を完了したのであれば、案件自体を完了させる必要があります。）

したがって、「案件詳細ページ」の「完了」ボタンを押したときと同じ手順を辿れるように実装していただく必要があるかと思います。（気づきが遅れ申し訳ありません。）
「完了」ボタンを押すとモーダルが表示され、いずれを選んでも上記が矛盾なく処理されるようになっています。（そのはずです笑）。ただ、現在実装済の部分は完了日を本日に限定していましたが、タスクの中でもっとも遅い完了日を入れるためにメソッドを改良する必要があるかもしれません。

ここは時間がかかりそうですので別プルリクで構いません。
complete_stepメソッドの改良は、私が提案してもよろしいでしょうか？

2020-10-05 02:23 UTC, taniryuu requested changes
確認しました！
コメントを１件残してますので確認お願いします。

2020-10-05 12:14 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +      #start_step(@lead, @step)
start_stepメソッドの中にparams[:step][:scheduled_complete_data]の記述があると思いますが、まさにこのparamsが無いことでstart_stepメソッドが使えないということなのですが、何か見当違いなことを言ってますでしょうか？

2020-10-05 12:35 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
>        update_steps_rate(@lead)
complete_stepメソッドを「案件詳細ページ」の「完了」ボタンを押したときと同じ手順にするのは、かなり手数がかかるのではないでしょうか？それとも簡単に呼び出すことができるのでしょうか？
ここは時間がかかりそうなので別プルリクでお願いします。
complete_stepメソッドの改良の提案もよろしくお願いします。

2020-10-05 12:45 UTC, ruffini47 commented on app/views/leads/tasks/_tasks_index.html.erb
> +      <div class="panel-heading">
確かにインデントがずれていて不必要なdivの閉じタグが入っていました。インデントを修正し、108行目を削除します。

2020-10-05 15:02 UTC, ruffini47 commented
鈴木（文）さんの２件のコメントに対する修正と、
谷口さんの１件のコメントに対する修正をしpushしました。
ご確認下さい。

2020-10-05 22:32 UTC, fumihisasuzuki requested changes
修正ありがとうございます！適用できたようで良かったです。コードもだいぶスッキリしたと思います。
1点、リファクタリング提案がありますので、そこが修正されたらマージでよろしいでしょうか。

確かに、complete_stepメソッドを「案件詳細ページ」の「完了」ボタンを押したときと同じ手順にするのは、かなり面倒そうな印象を受けるかと思います。。。
ただ、前述したとおり、進捗レコードの完了処理を単体で行うと、案件レコードとの矛盾が生じます。タスクの変更処理を行ったときに、進捗レコードとの矛盾が生じないようにする処理と同じように、進捗の変更処理を行ったときも、案件レコードとの矛盾が生じないようにする処理が必要です。そこが自動で出来ないなら、システム化しているメリットが大きく失われると考えます。
そのためには、モーダルを呼び出す必要があります。少なくとも、ユーザーに「今の進捗を完了した後に何をするのか」を選ばせる画面へ遷移する必要があります。
「現状のcomplete_stepメソッドとモーダルは関連性があるのでしょうか？」に対しても、答えはYesです。
「今の進捗を完了した後に何をするのか」を選ばせる画面で、ユーザーがどの選択肢を選んでも、その過程でcomplete_stepメソッドが働いて、完了処理ができるように実装してあります。

上記完了処理は、もちろん、別プルリクで構いません。不明点や既存メソッドの改良依頼などありましたらお気軽にお申し付け下さい。
私の方でも反省点がありまして、今、「完了」ボタンが「案件詳細ページ」にベタ打ちになっているので、使い回しやすいよう、パーシャルに分けておく必要があるな、と思いました。次のプルリクで出せるように致します。
ちなみに、complete_stepメソッドの改良の提案は、既にこのブランチにもマージしていただきました。既にそれを利用していただいた形です。

以上、本プルリクでは1点だけ、修正をお願い致します。

2020-10-05 22:32 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +        end
リファクタリングの提案です。
case～end全体をifで分岐していただいたようですが、ここで異なるのはscheduled_complete_dateを更新する値だけですよね？その場合、更新する値をif文で一度変数に入れてから、その変数でupdate_attributesすることでコード量がぐっと減ると思います。例えば、下記のような形です。
```
scheduled_complete_date = params[:step].present? ? params[:step][:scheduled_complete_date] : (l Date.current)
case ～
when ～
  ～update.attributes(～, scheduled_complete_date: scheduled_complete_date, ～）
```

ただ、理想としては、ここもユーザーに完了予定日を入力してもらって開始処理をする方が良いなと思いました。
なぜなら、これって、(l Date.current)を強制更新しているので、ユーザーが既に完了予定日を入力していた場合、上書きされてしまうのですよね？それはユーザー視点で考えると、不本意なのではないかと考えられますので。
パーシャルがあるので、それを有効利用していただけたらと思います。
<%= render 'leads/step_statuses/start', step: @step, completed_id: nil, button_name: "開始" %>

今回のプルリクでは、冒頭のリファクタリングまでで良いかと思います。
パーシャルを使ってユーザーに完了予定日を入力させるのは、別プルリクでお願いできたらと思いますが、いかがでしょうか？

2020-10-06 01:38 UTC, taniryuu approved these changes
確認しました！
私からはマージしてOKです。

2020-10-06 06:33 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +        end
case～end全体をif分岐していたところを変数scheduled_complete_dateを使って書き直しました。
また、パーシャル<%= render 'leads/step_statuses/start', step: @step, completed_id: nil, button_name: "開始" %>
を利用して、ユーザーが完了予定日を入力できるように変更しました。

2020-10-06 06:39 UTC, ruffini47 commented
start_stepの部分は鈴木（文）さんの指摘通りにユーザが完了予定日を入れられるように変更しました。
しかし、complete_stepも同様にしようとしましたが、step_statuses_complete_step_urlにリダイレクト後、モーダルを開こうとしましたが、開かませんでした。モーダルをsteps#show以外ても開けるような修正をお願してもよろしいでしょうか？その際、完了日をタスクの完了日の内最も遅い完了日にできるようにしていただければ幸いです。

2020-10-06 12:33 UTC, fumihisasuzuki requested changes
start_step時に完了予定日の入力フォームの実装、ありがとうございました。
また、これも次回以降で良いと思いますが、今後は、「途中で戻るボタンを押したらどうなるか」も考えながら実装していただけると幸いです。最悪、エラーにならなければ良いですが、レコード間で矛盾がある状態になってしまうようだと良くありません。

＜complete_stepについて＞
チャレンジいただきありがとうございます。前回のコメントでも記載しましたが、次回以降のプルリクで構いません。（私の宿題もありますし。）
ただ、実装に到っていない変更は、マージすべきでないと考えますが、谷口さん、PMとしていかがでしょうか？

2020-10-06 12:33 UTC, fumihisasuzuki commented on app/views/leads/steps/step_statuses_start.html.erb
> +<%= render 'leads/step_statuses/start', step: @step, completed_id: nil, button_name: "開始" %>
ここで、ユーザーが戻るボタンを押すとどうなるでしょうか。

2020-10-06 12:33 UTC, fumihisasuzuki commented on app/views/leads/steps/step_statuses_complete.html.erb
> +
これが開かなかったということですね？（私の方でパーシャルを作成中ですので少々お待ちください。）
成功しなかった変更は、コミット及びマージすべきでないと思いますので、コミットを取り下げていただけますか？

また、ユーザーにとっては、わざわざこのページに遷移させられて、ボタンをひとつ押すだけというのは不便ではないでしょうか？
前の画面にボタンを表示できませんか？

2020-10-06 13:24 UTC, taniryuu commented
>>実装に到っていない変更は、マージすべきでないと考えますが

コメントを残してもらえるか、丸ごとコメントアウトしてもらえれば
developへのマージですので大丈夫かと思ってます。

画面上でエラーがでなければについては同意です。こちらの手動テストがやり辛いので。
テストしてみてエラーがでなくてもログを見てみるとN＋1問題とかrenderがやたら走ってたりといろんな状況があるので...
その時はGithubのissueで修正依頼など試す良い機会ということで思ってます。

2020-10-06 13:31 UTC, fumihisasuzuki commented
谷口さん、ご確認ありがとうございます。
現状、エラーは出ていなさそうですのでマージ致します。（新しく作ったリダイレクト先はコメントアウトしていただいているので）

松本さん、長らくお付き合いいただいてしまい申し訳ありませんでした。
とりあえず、本プルリクはこれにてマージ致します。

2020-10-06 13:32 UTC, merged