Feature/notification logic
taniryuu/Rer_Pro pull request #90
Opened 2020-10-06 02:10 UTC by taniryuu

# ※マージはしないでください。
通知の作り方を失念してたので少しずつ進めてます。
アドバイス等あると思うのでよろしくお願いします。
## やったこと
## やらないこと
* このプルリクでやらないことは何か?(あれば。無いなら「無し」でOK)
## できるようになること(ユーザ目線)
* 何ができるようになるのか?(あれば。無いなら「無し」でOK)
## できなくなること(ユーザ目線)
* 何ができなくなるのか?(あれば。無いなら「無し」でOK)
## 動作確認
* どのような動作確認を行ったのか? 結果はどうか?
## その他
* レビュワーへの参考情報(実装上の懸念点や注意点などあれば記載)

2020-10-06 07:39 UTC, ruffini47 commented on app/controllers/users_controller.rb
> +      if Date.current.to_s > lead.scheduled_contract_date
この条件は契約予定日に近づいているというより、過ぎてしまっている条件になっていませんか？

2020-10-06 07:58 UTC, ruffini47 approved these changes

2020-10-06 07:59 UTC, ruffini47 commented
確認しました。２点コメントしました。

2020-10-06 13:05 UTC, taniryuu commented on app/controllers/users_controller.rb
> +      if Date.current.to_s > lead.scheduled_contract_date
現状そうなってますね。はい

2020-10-06 13:23 UTC, fumihisasuzuki commented on app/controllers/application_controller.rb
> +  def set_member
set_users
って他にあるんでしたっけ？
あえてset_member(s)を使っていた理由ってありますか？
ないなら、set_usersの方が素直だな、と。@usersをセットしているわけですし。

2020-10-06 13:26 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +  end
これはメソッドですか？アクションですか？（routes.rbを変更してないところから察するに、メソッドでしょうか？）
何をどうするメソッドでしょうか？

2020-10-06 13:31 UTC, taniryuu commented on app/controllers/application_controller.rb
> +  def set_member
set_memberなら企業内に所属しているUserで括ってるんだなと
Userモデルを見に行かなくてもわかりやすくないですかね？
set_usersは作るならUser.allを入れる時じゃないですか？。そんなイメージです

2020-10-06 13:40 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +  end
先に説明すると
users#showに全ユーザー共通の自分の案件が遅延してる通知を表示させるロジックを組もうかなと

なのでここに上長視点の案件新規作成時と案件の完了予定日を変更した通知を取ってくるロジックを作ろうかなと考えてます。
正直これで良いのかわからないです

2020-10-07 04:35 UTC, fumihisasuzuki commented on app/controllers/application_controller.rb
> +  def set_member
「set_member」を見て、「企業内に所属しているUserで括ってる」とわかるかどうかは、人によりそうです、、、少なくとも私はUserモデルを見に行かないとわかりませんでした。
むしろ、Qiitaなどのサイトを見ていると、memberモデルを使っているケースもあるようなので、「Userモデルとは別にMemberモデルがある？？」と思われてもつまらないなと思い、コメントさせていただきました。

「企業内に所属しているUserで括ってる」ことを伝えたいなら、
set_users_in_company
set_companys_users
などはいかがでしょうか？

2020-10-07 04:48 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +  end
一応、私の中にはイメージがあるのですが、、、共有しますので少々お待ちください。

2020-10-07 11:57 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +  end
イメージをコードにしていってから、改めて本プルリクの内容をみたら、ほとんど同じ内容になりそうでした！
users#showにbefore_action noticeしておくイメージですね、また気になったところがあったらコメントさせていただきます。。。

2020-10-09 07:50 UTC, taniryuu commented on db/seeds.rb
> +        notice_change_limit: true,
テストの為にtrueにしてます。
notice_change_limitはデフォルトでtrueなのでこのままにしてます。

2020-10-09 11:37 UTC, ruffini47 approved these changes

2020-10-09 11:38 UTC, ruffini47 approved these changes

2020-10-09 11:39 UTC, ruffini47 commented
確認しました。
問題なさそうです。

2020-10-10 00:03 UTC, fumihisasuzuki requested changes
新しいプッシュがありましたのでコメントしました。
なんか、編集途中的な雰囲気もしたので、これからリファクタリングされるおつもりでしたら申し訳ありません。
ここに挙げる以上は、レビューした方が良いのかな、と思ってしているのですが、「まだ編集中のためレビュー不要」であれば、プッシュした際にその旨コメントしていただけると、どういう意図のプッシュなのかわかり、助かります。

このような、共有のためのプルリクが初めてなので、手探りで申し訳ありませんが、よろしくお願い致します。「こういうプルリクはこういう感じで運営していくものだ」的なソースがありましたら教えていただけると幸いです。

＜追記＞
冒頭のコメントを編集して追記しておいてくださったんですね、すみません、気づきませんでした・・・

2020-10-10 00:19 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +                  .where(superior_id: current_user.id)
わかりました。
コメント修正しておきます。

2020-10-10 00:23 UTC, taniryuu commented on app/controllers/notifications_controller.rb
>          end
ほんとですね。
seed.rbを全部trueに変えてる状態だったのでミスに気がつきませんでした。
カウントするだけなので変数に入れます。

2020-10-10 00:25 UTC, taniryuu commented
seed.rbにはコメント追加しておきますね。
このプルリクの運用法についてもどこかのページでみたのを模倣してるだけなのでURL探しておきます。

2020-10-10 00:47 UTC, taniryuu commented on app/views/users/show.html.erb
> +<% end %>
昨日Googleドライブで探してみたのですが通知に関するviewの構想練り忘れてませんかね？
ちょっと見つからなかったです。
康平さんも交えてミーティングして必要そうな表示を残したいですね...

新しくページを作るならviewとroutes.rbを編集
または通知を表示するモーダルをそれぞれの通知に使用するとかですかね？

2020-10-10 01:00 UTC, fumihisasuzuki commented on app/views/users/show.html.erb
> +<% end %>
現状、10/1にchatworkでお送りした絵しかないと思います。
それで実装して、ペルソナにコメントもらって改善していくのが現状最速かと思料します。

そうですね、モーダルでも良さそうです！

2020-10-10 02:02 UTC, taniryuu commented
@fumihisasuzuki 
運用法について参考にしてたページが見当たらなくて改めてググってみたのですが
Work In Progress (WIP)という手法みたいです。
完全に模倣できてませんでしたね。すいません。
参考:https://engineer.recruit-lifestyle.co.jp/techblog/2017-02-07-code-review/

2020-10-12 11:42 UTC, taniryuu commented
追加変更ファイルをpushし、コメントを更新しました。
チェックが済んだら今度はマージしても大丈夫です。

レビューよろしくお願いします。

2020-10-12 22:40 UTC, fumihisasuzuki requested changes
6点コメントしました。ご確認よろしくお願い致します。

2020-10-12 22:40 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +        @create_notices = leads.where(notice_created: true)
`@create_notices`をインスタンス変数にした理由はありますか？
この変数はuserでeachしているので書き変わりますし、この場で使うだけなら`create_notices`（インスタンス変数にする必要はない）と思いますがいかがでしょうか？
もしviewで使うなら、@create_notices_listがあるのでこれで十分と思ってました。

ただ、user毎に@create_notices_listが欲しいなら、それはuserを引数として別に作成する必要がありそうです。

@limit_change_noticesや@others_limit_noticesも同様と思いますのでご確認ください。

2020-10-12 22:40 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
>            @create_notices_user_num.push(leads.select(:user_id).distinct)
ここはuserでeachしている中ですよね？単に
`@create_notices_user_num.push(user.id)`
とリファクタリングできませんか？

@limit_change_notices_user_numや@others_limit_notices_user_numも同様です。

2020-10-12 22:40 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +        end
scheduled_contract_dateは、「契約予定日」で、以前こうさんと話せた際に、契約予定日は決まっていないこともあり、空白を許可するという仕様で決定したと思います。（なので、空白の場合があります。）
むしろ、scheduled_resident_date（入居予定日）と、scheduled_payment_date（入金予定日）はpresense: trueですので、こちらは通知対象にすることが必要です。

あと、これは少しロジックを考えなくてはいけないのですが、Step（進捗）のscheduled_complete_dateが迫っているときも通知が必要です。
（今確認したら、基本設計書には、タスクの完了予定日も通知するようなことが書いてありますが、それもいちいち通知していたら通知だらけになってしまうだろう、ということで、タスクは通知しないことになった記憶がありますが・・・）

2020-10-12 22:40 UTC, fumihisasuzuki commented on app/controllers/users_controller.rb
> +    limit_date = Date.current + @user.notified_num
この定義はコントローラで計2回出てきているので、モデルに
```
def limit_date
  Date.current + self.notified_num
end
```
などと定義して、コントローラでは
`@user.limit_date`
と使えるようにリファクタリングしておくのはアリな気がします。

2020-10-12 22:40 UTC, fumihisasuzuki commented on app/views/users/show.html.erb
>  <% end %>
リンクを作成して、「期限変更リスト」ページへ遷移するのはまた別プルリクですかね？
とりあえず、一覧で表示しているということですね？

2020-10-12 23:12 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +        @create_notices = leads.where(notice_created: true)
いろいろテストしていたものを変更し忘れてました。
後ほど修正ファイルをpushします。

2020-10-12 23:12 UTC, taniryuu commented on app/controllers/notifications_controller.rb
>            @create_notices_user_num.push(leads.select(:user_id).distinct)
なるほどほんとですね。

2020-10-12 23:12 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +        end
まだテストしてないですが
`leads.where("scheduled_contract_date <= ?", limit_date)`
で期限直前でない案件は取得されない＝空白は除外みたいにSQLは動きませんかね？

2020-10-12 23:12 UTC, taniryuu commented on app/views/users/show.html.erb
>  <% end %>
はい。必要な値を取れてるか、renderの表示はうまくできてるかの表示です。

2020-10-13 03:01 UTC, fumihisasuzuki commented on app/controllers/notifications_controller.rb
> +        end
空白でエラーやバグにならないのであれば、良いと思います。

2020-10-13 04:29 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +        end
テストしてみたのですが空白は取得対象になってしまいます。
直しておきます。

2020-10-13 06:04 UTC, taniryuu commented on app/controllers/notifications_controller.rb
> +        others_limit_notices = leads.where.not(scheduled_contract_date: "").where("scheduled_contract_date <= ?", user.limit_date)
""が入っているので現状where.not(scheduled_contract_date: "")で繋いでます。
表示の手動テストで確認しました。

2020-10-13 21:47 UTC, fumihisasuzuki commented
修正ありがとうございます。確認しました。修正いただいた箇所は問題ないと思います。

ただ、1点、
https://github.com/taniryuu/Rer_Pro/pull/90#discussion_r503564865
でもコメントしましたが、締切間近の通知対象は、scheduled_contract_date「契約予定日」だけで良いのでしょうか？
```
scheduled_resident_date（入居予定日）
scheduled_payment_date（入金予定日）
Step（進捗）のscheduled_complete_date（完了予定日）
```
は締切間近の通知対象にしないですか？

2020-10-13 23:21 UTC, taniryuu commented
見落としてました🙇‍♂️
完了予定日は案件の完了予定日じゃなくて
ひとつの案件に対して各予定日の通知を取得する感じですね。

ちょっと覚えてる範囲で良いのですが
この各予定日の完了予定日間近の通知を表示するのも全部本人、上司に取得させた方がいいですかね？

2020-10-13 23:49 UTC, fumihisasuzuki commented
もしかしたら、誤解があるかもしれませんが、現在、案件（Leadモデル）に、「完了予定日」というカラムはありません。
強いて言えば、入居予定日がそれに該当すると思います。
あるいは、最後の進捗の完了予定日がそれに該当すると思います。

進捗（Stepモデル）には「完了予定日」というカラムがあります。この締切間近を通知するのが、本来の通知の目的だったと思います。（「進捗の遅れている案件が知りたい！」上司のためのアプリだったと思います。）
私は、なんなら通知するのは、この「進捗モデルの完了予定日（Step.scheduled_completed_date）」だけでも良いのではないか、とすら考えていました。

このあたり、決定事項がふわふわしているような感じがするので、ミーティングで話し合いますか？

> この各予定日の完了予定日間近の通知を表示するのも全部本人、上司に取得させた方がいいですかね？

そうですね、期限間近の通知は、本人、上司の両方へ通知することで良いと、私は思います！

2020-10-14 00:36 UTC, taniryuu commented
ミーティングで決めるのが早く済みそうですね。
チーム内で決定させといてフィードバックを得るのが最短でしょうし。
先に康平さんにも質問投げてたので返信あったら共有します。

2020-10-14 03:43 UTC, fumihisasuzuki commented
では、その決定を実装するのは別プルリクの方が良いですかね。
マージはして、ブランチは消さずに残しておきます。

2020-10-14 03:44 UTC, merged