Embed form and finish button 2
taniryuu/Rer_Pro pull request #92
Opened 2020-10-10 13:39 UTC by ruffini47

## やったこと
・タスク状態によって制御する３つの画面でラジオボタンをやめて画面遷移せずに処理が完結するようにしました。
・済リスト、中止リストの件数を表示しました。
・完了日の未来の日付禁止バリデーションをapp/models/application_record.rbのものを使いました。
・app/models/application.rbのscopeとstatus?(status_name)メソッドを使って書き直しました。
・change_status_or_complete_taskの「進捗を未にする」、「すべてのタスクを未にする」でtransactionを使用しました。
## やらないこと
・taskのバリデーションをより厳しくすることはまだやっていません。
## できるようになること(ユーザ目線)
・タスク状態によって制御する画面の後、余計な画面遷移しなくてよくなる。
## できなくなること(ユーザ目線)
* タスク状態によって制御する画面でラジオボタンは使えなくなる。
・基本的なtaskのCRUD、チェックボックス、中止ボタン、復活ボタンが機能すること。タスク状態によって制御する画面で正しくtask,stepの状態を変更できること。
* どのような動作確認を行ったのか? 結果はどうか?
## その他
* レビュワーへの参考情報(実装上の懸念点や注意点などあれば記載)

2020-10-11 09:23 UTC, taniryuu requested changes
確認しました！
ロジックを追うのが難しく実際に触ってみないとわからない部分が多いです。
インデントで気になる部分があったのでコメントしました。
修正お願いします。

2020-10-11 09:23 UTC, taniryuu commented on app/views/leads/tasks/_tasks_index.html.erb
> +        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><h4 style="display:inline;"><%= "中止 リスト" %></h4></a>
`<%= "中止 リスト" %>`
ここは<%= %>で括ってますが
変更前の中止 リストだと何か不具合があったところですか？

2020-10-11 09:23 UTC, taniryuu commented on app/views/leads/tasks/edit_complete_or_continue_step.html.erb
> + <%= render 'leads/step_statuses/start', step: @step, completed_id: nil, new_task: true, button_name: "開始" %>
renderはインデントいらないと思うのですがどうですかね？

2020-10-11 09:23 UTC, taniryuu commented on app/views/leads/tasks/edit_continue_or_destroy_step.html.erb
> + <%= button_to '削除', statuses_destroy_step_step_path(@step), method: :get %>
2,5行目も同じですね。

2020-10-11 09:23 UTC, taniryuu commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +  <%= button_to '更新', statuses_make_all_tasks_not_yet_step_path(@step), method: :get %>
2,5,8,11行目もインデントは不要かと思います。

2020-10-11 09:23 UTC, taniryuu commented on app/views/leads/step_statuses/_start.html.erb
> +  <%= form.hidden_field :new_task, :value => new_task %>
`:value => new_task`
は
`value: new_task`
に書き方も統一できるかと思います。
ちょっと試してみてください。

2020-10-11 09:23 UTC, taniryuu commented on app/controllers/leads/application_controller.rb
> +        if new_task == "true"
8~21行目までインデントひとつ多く入ってます。

2020-10-11 09:50 UTC, fumihisasuzuki requested changes
レビュー遅れまして申し訳ありません。
追加してくださった４つのアクションのうち、２つは全く同じ内容のアクションが既にありますので、既存のものが使えないかご検討お願い致します。
また、１つはアクション名と内容に乖離があるように思われるので、ご確認をお願い致します。

new_taskの渡し方については、どのように考えられて、現在どのように実装されているのか意図までわかりにくいので、本日の定例で少しお聞かせいただけると幸いです。

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +
statuses_destroy_stepアクションは何のために追加したのでしょうか？
71行目～73行目のdestroyアクションを使えませんか？

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +  end
leads/steps_statusesコントローラの#cancelアクションが全く同じことをしていますので、そちらを利用できませんか？

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +  end
97行目のコメントとアクション名は「すべてのタスクを未にする」
99行目のコメントとコードの中身は「未のタスクを全て完了にする」
全く違うことをやっているように見えますが・・・
どちらが正でしょうか？

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/controllers/leads/steps_statuses_controller.rb
>    end
`if [:step].present?`に対する、elseの処理は必要ありませんか？

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +~
`&#9312`とは何ですか？

2020-10-11 09:50 UTC, fumihisasuzuki commented on config/routes.rb
> +        get 'statuses_make_all_tasks_not_yet'
コントローラのところでもコメントしましたが、`statuses_destroy_step`と`statuses_make_step_inactive`は既存のもので代用できないか、`statuses_make_all_tasks_not_yet`はメソッド名と処理内容に乖離がないか、ご検討をお願い致します。

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/views/leads/step_statuses/_start.html.erb
> +<%= form_with(url: start_step_path(step, completed_id: completed_id), model: step, local: true, new_task: new_task) do |form| %>
ここでnew_task:とパラメータを渡すと、どのような挙動になるのでしょうか？
comoleted_idを渡す挙動と異なりますか？（どのような違い、メリットがありますか？）

2020-10-11 09:50 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +  def start_step(lead, step, new_task)
ここはちょっと要協議ですが、ここで引数にnew_taskを渡すということは、start_stepを使用するときに常にnew_taskがtrueかfalseか渡すということになりますが、そこまで必要でしょうか？
params[:completed_id]のように、params[:new_task]を渡すことで、渡されたときだけ8～10行目の処理をして、何もしなければそこはスルー、のようにできないでしょうか？

2020-10-12 11:41 UTC, ruffini47 commented on app/views/leads/tasks/_tasks_index.html.erb
> +        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><h4 style="display:inline;"><%= "中止 リスト" %></h4></a>
不具合ではないですが、上のToDoリストのところで<Step～>完了まであと～件のところで<%= %>で括ったところに合わせました。

2020-10-12 11:43 UTC, ruffini47 commented on app/views/leads/tasks/edit_complete_or_continue_step.html.erb
> + <%= render 'leads/step_statuses/start', step: @step, completed_id: nil, new_task: true, button_name: "開始" %>
renderのところはインデントはいらないですね。修正しておきます。

2020-10-12 11:44 UTC, ruffini47 commented on app/views/leads/tasks/edit_continue_or_destroy_step.html.erb
> + <%= button_to '削除', statuses_destroy_step_step_path(@step), method: :get %>
同じく修正しておきます。

2020-10-12 11:45 UTC, ruffini47 commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +  <%= button_to '更新', statuses_make_all_tasks_not_yet_step_path(@step), method: :get %>
そうですね。修正しておきます。

2020-10-12 11:52 UTC, ruffini47 commented on app/views/leads/step_statuses/_start.html.erb
> +  <%= form.hidden_field :new_task, :value => new_task %>
`value: new_task`で問題なく動きました。`value: new_task`の書き方で統一しておきます。

2020-10-12 11:57 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +        if new_task == "true"
if new_task == "true" ～ endをトランザクションの中に入れたときに誤ってインデントが１つ深くなってしましました。
8~21行目でインデントをひとつ浅くしておきます。

2020-10-12 12:08 UTC, ruffini47 commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +~
①をHTMLで使用するために１０進数で表したものです。

2020-10-12 13:19 UTC, ruffini47 commented on app/views/leads/step_statuses/_start.html.erb
> +<%= form_with(url: start_step_path(step, completed_id: completed_id), model: step, local: true, new_task: new_task) do |form| %>
start_step_pathの中にパラメータnew_task:を入れても同様なのでそのように修正しました。違いはcontrollerでのパラメータの受け取りがparams[:task][:new_task]からparams[:new_task]に変わるくらいです。

2020-10-12 13:25 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +  def start_step(lead, step, new_task)
明示的に引数としてnew_taskを渡す必要はないですね。params[:completed_id]と同じように渡された時だけ処理して、nilのときはスルーのするように変更しました。進捗を開始したとき「未のタスク」がなければ必ずタスクを生成するもしくは、ユーザーに強制入力させるかどうかは、次のプルリクで考えることにします。

2020-10-12 13:30 UTC, ruffini47 commented on app/controllers/leads/steps_statuses_controller.rb
>    end
下のコメントに書いたように、new_taskを引数に渡す必要がなくなりましたので、if文は削除して、startアクションはstart_step(@lead, @step)を実行するだけの以前の状態に戻しました。

2020-10-12 13:51 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +  end
「未のタスクを全て完了にする」が正しいです。97行目のコメントは正しくは「「未」のタスクをすべて「完了」とする」で、アクション名は「statuses_make_all_not_yet_tasks_completed」としました。うっかりミスです。失礼しました。

2020-10-12 14:07 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +
leads/steps#destroyアクションはルーティングでdeleteメソッドになっていると思います。以前のプルリクでも同様の記述があったと思いますが、deleteメソッドは

2020-10-12 14:26 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +
button_toで遷移先としてleads/steps#destroyを指定したとき、ルーティングでleads/steps#destroyアクションはdeleteになっているため直接遷移できません。以前はラジオボタンからupdate_continue_or_destroy_stepアクションに飛んでからそこでdestroy_step(@lead, @step)メソッドを呼んでいました。今回も直接leads/steps#destroyへは遷移できないので、一度getメソッドであるstatuses_destroy_stepアクションに飛んでからそこで、destroy_step(@lead, @step)メソッドを呼んでいます。

2020-10-12 14:48 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +  end
上のコメント同様button_toの遷移先をcancel_step(@step), method: :patchにしてleads/steps_statuses#cancelアクションを利用したら、進捗を保留に出来ました。statuses_make_step_inactiveメソッドも必要なかったですね。

2020-10-12 14:55 UTC, ruffini47 commented on config/routes.rb
> +        get 'statuses_make_all_tasks_not_yet'
上のコメントにも書きましたように、`statuses_destroy_step`と`statuses_make_step_inactive`はleads/steps#destroyアクションとleads/steps_statuses#cancelアクションで代用できました。`statuses_make_all_tasks_not_yet`メソッドは`statuses_make_all_not_yet_tasks_completed`にメソッド名を変更しました。

2020-10-12 15:26 UTC, ruffini47 commented
コメントを確認し、インデントの修正、メソッド名、コメントの変更、既存のアクションを利用、new_tasks変数の扱いを変更し、プッシュしました。
御確認をよろしくお願いします。

2020-10-12 21:05 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +
Viewにおけるbutton_toで遷移先と、Controllerにおけるredirect_toの遷移先とでは要件が全然異なるという認識です。
使えたなら良かったです！

2020-10-12 21:12 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +  end
修正ありがとうございます。
ちょっと長いので、`complete_all_tasks`などでいかがでしょうか？

また、このアクションは、タスクに対して行われる処理がメインですので、task_controller.rbに書かれるべきと思いますが、あえてsteps_controller.rbに記載した意図はなんでしょうか？

2020-10-12 21:14 UTC, fumihisasuzuki commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +~
勉強になりました。ありがとうございます。

2020-10-12 21:18 UTC, fumihisasuzuki commented on app/views/leads/step_statuses/_start.html.erb
> +<%= form_with(url: start_step_path(step, completed_id: completed_id), model: step, local: true, new_task: new_task) do |form| %>
params[:new_task]の方がシンプルで良いですね。

2020-10-12 21:48 UTC, fumihisasuzuki requested changes
修正、ありがとうございます！

気になったところを4件、新たにコメントしました。
修正依頼にしておりますが、現状問題なく作動しているなら、リファクタリングは次回以降のプルリクにしていただいても構いませんので、その場合はその旨返信いただければと思います。

また、既にしたコメントにも、返信ない箇所ありましたので、スタンプで構いませんので読んだ旨お知らせいただけると幸いです。今回のコミットの内容を読み込む限り、読んでいただいたのだろうとは判断できましたが。

2020-10-12 21:48 UTC, fumihisasuzuki commented on config/routes.rb
> +        get 'statuses_make_all_not_yet_tasks_completed'
`statuses_destroy_step`と、`statuses_make_step_inactive`が不要になったようでしたら、controllerの方のコードも削除をお願い致します。

また、`statuses_make_all_not_yet_tasks_completed`アクションは、メソッドgetで動いたのでしょうか？対応するhtmlがないように思いますが・・・コントローラの処理をするだけなら、メソッドはpatchになるかと思います。

2020-10-12 21:48 UTC, fumihisasuzuki commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
>  ~
2行目と、11行目は、method: :getで動いたのでしょうか？対応するviewはありましたっけ？
処理するだけならpatch（場合によってはput, delete）でないと動かないと思っていましたが・・・

2020-10-12 21:48 UTC, fumihisasuzuki commented on config/routes.rb
>        member do
これはプラスアルファのコメントです。
前から気になっていたのですが、32行目～38行目のルーティングは、tasks/を外して40行目～44行目のルーティングの中に入れることはできないのでしょうか。rails routesを見る限り、同じになりそうなので確認していただけませんか？

2020-10-12 21:48 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +      end
記載した場所を変えたことに何か意図がありますか？

今後、「進捗中の進捗には、未のタスクが必要」のバリデーションを組むなら（というか、一昨日のミーティングの流れからすると組むことになりそうです。）、今までの位置（8～10行目）の方が良かったです。
11～21行目より後にしてしまうと、step.updateで上記バリデーションに引っかかる可能性があるので。
上記バリデーションはstep.valid?のときだけ作動するようにしておけば回避できるので、必須ではないのですが・・・

何かお考えがありましたらお聞かせください。

2020-10-12 23:19 UTC, taniryuu commented on app/views/leads/tasks/_tasks_index.html.erb
> +        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><h4 style="display:inline;"><%= "中止 リスト" %></h4></a>
rubyの言語をhtmlで使うときに<%= %>で括るような認識なんですが単に文字列だけなら括る必要はない気がします。
5行目のようにrubyの変数を追加する予定なら現状このままで大丈夫です。

2020-10-12 23:25 UTC, taniryuu reviewed
コメントと修正ありがとうございます。
pushされた修正ファイルに気になった箇所ありましたのでコメント入れました。
確認お願いします。

2020-10-12 23:25 UTC, taniryuu commented on app/views/leads/step_statuses/_start.html.erb
> +  <%= form.hidden_field :new_task, value:  new_task %>
すみません
ちょっと細かいですがvalue:の後ろに半角スペースひとつ分多く入ってます。

2020-10-13 04:57 UTC, ruffini47 commented on app/views/leads/tasks/_tasks_index.html.erb
> +        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4"><h4 style="display:inline;"><%= "中止 リスト" %></h4></a>
単なる文字列なので<%= %>で括る必要はないですね。修正しておきます。

2020-10-13 05:08 UTC, ruffini47 commented on app/views/leads/step_statuses/_start.html.erb
> +  <%= form.hidden_field :new_task, value:  new_task %>
value:の後ろに半角スペースが２つ入っていました。１つに修正しておきます。

2020-10-13 05:43 UTC, ruffini47 commented on config/routes.rb
>        member do
32~38行目のルーティングはtask/を外してresource :tasks do member doの中に入れても同じように使えました。
わざわざtask/を付ける必要はなかったですね。

2020-10-13 06:09 UTC, ruffini47 commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
>  ~
対応するviewはありませんがredirectしているので2行目と11行目はmethod: :getで動いています。対応するviewがなく処理だけするならpatch(またはput,detele)にするのが基本でしょうか？それならばpatchメソッドの方が良いですね。patchで書き直しておきます。

2020-10-13 06:36 UTC, ruffini47 commented on config/routes.rb
> +        get 'statuses_make_all_not_yet_tasks_completed'
`statuses_destroy_step`アクションと`statuses_make_step_inactive`アクションはcontrollerから削除しました。対応するviewの無いアクションはpatchですね。修正しておきます。

2020-10-13 06:51 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +  end
`complete_all_tasks`だと「すべてのタスクを完了する」の意味に誤解されないでしょうか？少し長いですがアクション名はそのままにしておきます。

2020-10-13 06:53 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      end
確かにstep.updateバリデーションのことを考えたら新しいタスクを追加するコードは8～10行目の方が良いですね。位置を元に戻しておきます。

2020-10-13 07:57 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +  end
`statuses_make_step_not_yet`アクションをsteps_controllerに書いたので`statuses_make_all_not_yet_tasks_completed`アクションもsteps_controllerに書いたのですが、`tatuses_make_all_not_yet_tasks_completed`アクションはタスクに関するアクションなのでtasks_controllerに記載したほうが良さそうです。書き直しておきます。

2020-10-13 08:25 UTC, ruffini47 commented
谷口さんのコメントに対する対応、鈴木（文）さんの一つ前のコメントに対する対応１点と４つのコメントに対する対応４点をし、pushしました。御確認下さい。

2020-10-13 09:55 UTC, taniryuu approved these changes
確認しました。
修正ありがとうございます。
私の方からは問題なさそうでした。

2020-10-13 21:51 UTC, fumihisasuzuki commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
>  ~
いえ、method: :getでも動くのでしたら大丈夫です。私の勉強不足でした。getとpatchの違いについてもう少し調べてみます。ありがとうございます。

2020-10-13 22:16 UTC, fumihisasuzuki approved these changes
修正ありがとうございます。method: :getでも動くのでしたら、問題なかったのですが、余計な変更を強いてしまったようで申し訳ありませんでした。
（逆に、getでもpatchでも問題なく動くということでしょうか？？なんか不思議です。）

調べてみても、method: :getはページを取得して表示する（=Viewを表示する）、という一般的な記事しか出てこないので、何かわかりましたら教えていただけると幸いです。

2020-10-13 22:16 UTC, fumihisasuzuki commented on app/controllers/leads/tasks_controller.rb
> +                                        :edit_complete_or_continue_step, :edit_change_status_or_complete_task, :statuses_make_all_not_yet_tasks_completed]
やっぱり
`statuses_make_all_not_yet_tasks_completed`
は長いですね・・・
`complete_all_tasks`
など、もっとシンプルなアクション名をご検討ください。
別プルリクでも大丈夫かと思いますので、今回はマージしておきます。

2020-10-13 22:17 UTC, merged