案件の凍結処理、再開処理
taniryuu/Rer_Pro pull request #93
Opened 2020-10-11 04:19 UTC by fumihisasuzuki

## やったこと
* 案件の凍結及び再開処理
* 案件詳細ページが大きくなってきたので、部分ごとにパーシャル化
* 進捗の完了予定日を変更した際に、通知フラグをtrueにするコードを追加（現在コメントアウト中）
## やらないこと
* 通知フラグをfalseにする処理は追加していません。そちらが追加されたら、上記コメントアウトを外すことで考えております。
* そろそろ、どんな手動テストをすれば問題なしと判断できるか、明文化しておく必要があるな、と考えております。
## できるようになること(ユーザ目線)
* 案件の凍結処理
* 凍結または完了した案件の再開処理
## できなくなること(ユーザ目線)
* なし
## 動作確認
* 進捗の開始、完了、凍結、案件の完了、凍結、再開の流れを一通り行った。（上記でも書きましたが、「一通り」の内容を書き出しておく必要あり、と感じました。）
## その他
* メソッドも少し変更していますので、タスク関連のところでエラーを引き起こすかもしれません。ご確認いただけますと幸いです。

2020-10-11 09:52 UTC, taniryuu requested changes
確認しました。
flashの使い方でどんなUIになるのか気になって早く試してみたいです。
途中気になるところに気づきましたので忘れる前に修正お願いします。

2020-10-11 09:52 UTC, taniryuu commented on app/views/leads/step_statuses/_index.html.erb
> +          	  <%= "Step #{step.order}" %>
細かいですが半角スペースひとつ分多く入ってます。

2020-10-11 09:52 UTC, taniryuu commented on app/views/leads/steps/_steps_index.html.erb
> +  </td>
46行目は
`</tr>`
じゃないですかね？

2020-10-11 11:33 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>        check_status_completed_or_not(lead, step)
ここはcheck_status_inactive_or_not(lead, step)のチェックはいらないのでしょうか？

2020-10-11 11:41 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>        check_status_completed_or_not(lead, step)
ここもcheck_status_inactive_or_not(lead, step)は要りませんか？

2020-10-11 11:50 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +    elsif lead.status?("in_progress") && lead.steps_rate == 100 # ここから完了状態に揃える処理
ここでleadのstatusがinactiveである場合は考えなくて良いですか？

2020-10-11 13:18 UTC, ruffini47 commented on app/views/leads/steps/show.html.erb
> +      <%#= "（期限変更：上司未確認）" if @lead.notice_change_limit && @step.notice_change_limit %>
この行はコメントアウトでしょうか？

2020-10-11 13:19 UTC, ruffini47 approved these changes

2020-10-11 13:20 UTC, ruffini47 commented
確認しました。
何点か質問させていただきました。

2020-10-12 13:36 UTC, fumihisasuzuki commented
コメントありがとうございます！
修正、及び確認するので少々お待ちください！

2020-10-12 13:50 UTC, fumihisasuzuki commented on app/views/leads/step_statuses/_index.html.erb
> +          	  <%= "Step #{step.order}" %>
良く気づきますね！ご指摘ありがとうございます。
ただ、確認してみたらローカルではスペースの数が合ってるみたいです・・・タブではなく、前の行からエンター押して得られた位置にしてみましたがいかがでしょうか。

2020-10-12 13:51 UTC, fumihisasuzuki commented on app/views/leads/steps/_steps_index.html.erb
> +  </td>
ありがとうございます、修正しました！

2020-10-12 13:53 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
>        check_status_completed_or_not(lead, step)
24行目で同様の処理をしているため不要だったのですが、逆に、check_status_inactive_or_not(step)のチェックをすることでcase～whenの条件分岐が不要になるかもしれません。
ちょっと試してみます。

2020-10-12 13:56 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
>        check_status_completed_or_not(lead, step)
ここも、69行目で同じ処理をしているので不要と考えていました。
一応入れておく方が良いでしょうか？

2020-10-12 14:03 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +    elsif lead.status?("in_progress") && lead.steps_rate == 100 # ここから完了状態に揃える処理
むしろ、「leadのstatusがinactiveである場合」に、何も処理しないように変更しました。
その場合は、このメソッドではスルーさせて、check_status_inactive_or_notメソッドに役割を託しています。

2020-10-12 14:07 UTC, fumihisasuzuki commented on app/views/leads/steps/show.html.erb
> +      <%#= "（期限変更：上司未確認）" if @lead.notice_change_limit && @step.notice_change_limit %>
はい。
通知のtrue / falseの行き来ができるようになったらコメントアウトを外そうと思っています。
ここにこういう表示がいるのでは？という提案です。

2020-10-12 14:34 UTC, fumihisasuzuki commented
修正しました！ご確認をお願い致します。
app/controllers/leads/application_controller.rbは、これでもいけそうな気がしますが、いかがでしょうか？？

2020-10-12 23:28 UTC, taniryuu commented on app/views/leads/step_statuses/_index.html.erb
> +          	  <%= "Step #{step.order}" %>
見た感じきれいになってました！
ローカルと違う現象になるのは不思議ですね...

2020-10-12 23:35 UTC, taniryuu approved these changes
修正ありがとうございます。確認しました！
私からはマージしても大丈夫かと思います。

2020-10-13 12:12 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>        check_status_completed_or_not(lead, step)
69行目でinactiveに設定しているので必要ないですね。

2020-10-13 12:13 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +    elsif lead.status?("in_progress") && lead.steps_rate == 100 # ここから完了状態に揃える処理
inactiveの場合はcheck_status_inactive_or_notに託しているのですね。分かりました。

2020-10-13 12:14 UTC, ruffini47 commented
確認しました。私からも大丈夫です。

2020-10-13 23:14 UTC, fumihisasuzuki commented
松本さんのプルリクをマージしたことでコンフリクトが発生しましたので解消しました。
また、マージしたことで色々と不自然なUXも出てきましたが、それは次回以降のプルリクとさせてください。

2020-10-13 23:25 UTC, merged