Stricten task validation 2
taniryuu/Rer_Pro pull request #95
Opened 2020-10-22 15:17 UTC by ruffini47

## やったこと
<主な変更点>
どのようなtask操作、step操作をしたとしても、進捗中の進捗には「未」のタスクが存在するように、完了済の進捗には「未」タスクが無く、「完了済み」のタスクが存在するようにしました。
<細かい変更点>
status_make_all_not_yet_tasks_completeをより短いcomplete_all_tasksに変更しました。
## やらないこと
stepとtaskの同時フォーム更新。new_taskを生成するときにフォームに飛ばすこと。
## できるようになること(ユーザ目線)
taskの状態を保つようにユーザーに誘導するようにしました。
## できなくなること(ユーザ目線)
taskの状態を不正な状態にすること。
## 動作確認
taskのCRUD,stepのCRUDチェックボックス、中止ボタン、復活ボタンを押したとき正しく動作すること。
stepの開始ボタン、完了ボタン、保留ボタン、再開ボタン、直接編集、案件自体を凍結-再開を押したときに正しく動作すること。
## その他
step完了時に無限ループになることを回避するために、$through_check_status変数を導入しました。

2020-10-23 02:08 UTC, taniryuu reviewed
確認しました！
コメント書きましたので返信お待ちしてます。

2020-10-23 10:54 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +        Task.create!(step_id: @step.id ,name: "completed_task", status: 1, scheduled_complete_date: scheduled_complete_date, completed_date: params[:step][:completed_date])
そうですね。integer型じゃなくてstring型の方が可読性がいいですね。string型に修正しておきます。

2020-10-23 11:02 UTC, ruffini47 commented on app/controllers/leads/tasks_controller.rb
> +        redirect_to check_status_and_get_url(@step ,@step)
第一引数はtask状態をチェックすべきstepを表しています。第二引数はチェックした結果すべて当てはまらなかったときのリダイレクト先のstepを表しています。ここのURLはtask状態に依存して決まります。例えば@stepに「未」のタスクが無くて、「完了」のタスクがあれば、edit_complete_or_continue_step_task_urlになります。

2020-10-23 11:31 UTC, ruffini47 commented on app/views/leads/tasks/edit_complete_or_continue_step.html.erb
> +<h3><%= "<STEP#{@step.order}>#{@step.name}" %>:</h3>
そうですね。helperメソッドで対応してみます。

2020-10-23 23:48 UTC, fumihisasuzuki requested changes
遅くなり申し訳ありません。コメントしました。
変更の意図が読み切れなかった箇所も多かったので、見当違いのコメントであればご指摘いただけますと幸いです。

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +      step.completed_tasks_rate = 100 if step.status?("completed")
この1行を入れるのは望ましくないと、私は考えます。
なぜなら、タスクの完了率が100%でないのにも関わらず、step.statusが完了になってしまっている場合は、stepを"in_progress"に揃えるようにしているからです。
でないと、「未」のタスクがないにも関わらずstep.statusが完了になってしまう恐れがあり、松本さんの設定してくださったバリデーションに引っかかってしまいます。

この1行を入れないとどのような不具合が発生しますか？
それは、このcheck_status_completed_or_not(lead, step)メソッドを呼び出す前に、
complete_stepメソッドを呼び出すことで解決しませんか？

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +        flash[:danger] = "#{flash[:danger]}未完了のタスクがあるため、#{step.name}を完了にできません。" if step.status?("completed")
この変更は何のためでしょうか？
144行目の分岐で、「完了」状態の進捗は強制的に「進捗中」に更新しているので、
step.status?("completed")は常にfalseと考えられます。

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +
$through_check_statusを最初に定義しているのはどこでしょうか？？

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +        check_status_and_redirect_to(@completed_step, @step)
このupdate処理は、既にsave_and_errors_ofメソッドの中で行われておりますので不要です。

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +        check_status_and_redirect_to(@step, @step)
この分岐に行くのは、UXとしてどういった場合でしょうか？
言い換えると、ユーザーが何をしようとした際にこの分岐にいきますか？

完了済のタスクを自動生成する、というのは「進捗管理がしたい」というこのシステムの性質上、好ましくない気がします。
完了済のタスクがないのに、step.statusを「完了」にしようとしているユーザーに対しては、「タスクを設定して、全てのタスクを完了にしないと、進捗を「完了」状態にすることはできないよ」とエラーメッセージを返してあげるのはいかがでしょうか？？
完了済のタスクを自動生成してあげると、よくわからないタスクが完了状態で、進捗も完了状態で、完了状態がゆえにその後フォローされることがないので、そのまま見過ごされてわけのわからないデータが出来そうです。

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
>          end
ここの処理を外に出したのはなぜですか？
ここの処理を外に出すと、save_and_errors_ofメソッドが成功して、complete_stepメソッドが失敗した場合に、完了はできないけど新しい進捗はできるという矛盾が発生する恐れがあります。
また、complete_stepメソッドの後には、必ずcheck_status_completed_or_not(lead, step)をいれなくてはなりません。でないと、進捗が全て完了しているのに案件が終了にならないという矛盾が発生する恐れがあります。

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +        if !step.status?("completed") && step.tasks.not_yet.blank?
134行目が、157行目と表現が異なるのはなぜですか？
step.statusが"not_yet"や"inactive"の場合でも、タスクを新しくつくる必要があるでしょうか？？

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +          Task.create!(step_id: step.id ,name: "new_task", status: "not_yet", scheduled_complete_date: params[:step][:scheduled_complete_date])
この処理が何度も出てきている気がするので、メソッド化してDRYなコードにしませんか？

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/helpers/tasks_helper.rb
>  end
どちらかというと、step_helperに書く内容と思いますがいかがでしょうか？

2020-10-23 23:48 UTC, fumihisasuzuki commented on app/models/step.rb
> +
今回はまだ有効にしないんですね？

2020-10-24 08:25 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +
app/controllers/leads/steps_controller.rbの29行目になります。steps#showを呼び出すごとに初期化しています。

2020-10-24 08:27 UTC, ruffini47 commented on app/helpers/tasks_helper.rb
>  end
そうですね。step_helperに書くほうが良いですね。書き直しておきます。

2020-10-24 08:28 UTC, ruffini47 commented on app/models/step.rb
> +
はい。いまのところ必要ないのでコメントアウトしています。

2020-10-24 10:29 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
>          end
ここは一度同じようなコードをコメントアウトし、後で必要と気づき他の場所は復帰していたのですが、ここを復帰するのを忘れていました。ここは確かに外せないので元に戻しておきます。

2020-10-24 10:41 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +        check_status_and_redirect_to(@completed_step, @step)
ここでのupdate処理は、下の鈴木（文）さんのコメントの126-127行目を消去していたため、誤って必要と思っていたため、追加したコードでした。`errors << @completed_step.errors.full_messages unless complete_step(lead, @completed_step, @completed_step.latest_date)`をsave_and_errors_ofメソッドの中で復帰していたら、ここの50-51行目のコードは必要ないですね。消去しておきます。

2020-10-24 11:08 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +        flash[:danger] = "#{flash[:danger]}未完了のタスクがあるため、#{step.name}を完了にできません。" if step.status?("completed")
155行目は144行目の分岐は終わった後です。確かめたのですが、進捗が完了状態のとき、中止リストからToDoにタスクを復帰させ、完了済進捗編集時イベントを発生させて③の現在の進捗を保留にするを選んだとき、step.statusはinactiveになっており、そのとき不必要な「未完了なタスクがあるため進捗～を完了にできません。」というメッセージが表示されてしまいます。これを防ぐためにstep.status?("completed")がtrueのときのみこのメッセージを表示させるようにしました。

2020-10-24 11:48 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      step.completed_tasks_rate = 100 if step.status?("completed")
この１行を入れる理由は、例えば進捗１と進捗２を進捗中とし、進捗１を直接編集で完了を選んだ時、check_status_completed_or_notが呼び出されるのですが、この時stepを完了にしたいにもかかわらず、completed_tasks_rate<100になっているので自動的にstep.statusが進捗中に戻されてしまいます。それを防ぐためにこの１行を入れました。この１行を入れたとき、他のところで不具合が起こっているケースは、私がテストした限りはありませんでした。check_status_completed_or_notを呼び出しているupdateメソッドでstep.statusが"compteled"のときのみ
complete_stepを呼び出しても解決はできるとは思いますが、check_status_completed_or_notは複数回呼び出されていますのでそれぞれで呼び出し元で考えるより内部で解決したほうがいいように思います。

2020-10-24 12:30 UTC, fumihisasuzuki requested changes
check_status_completed_or_notメソッドは全体的に見直す必要がありそうです。
逆に言うと、今回コメントアウトしているタスクとのバリデーションがなかったがゆえに必要だったメソッドだったかもしれません。リファクタリングします。

2020-10-24 12:30 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +      step.completed_tasks_rate = 100 if step.status?("completed")
ありがとうございます。理解しました。

そのケースだと、進捗１に未完了のタスクがある場合、進捗１に未完了のタスクがあるまま進捗１が完了状態になってしまわないでしょうか？
その際は、バリデーションでひっかかるので大丈夫、ということでしょうか？？
そうしたら、この144行目～149行目までを削除する方が良いかもしれません。
ちょっと考えます。
そのバリデーションを取り入れることで、このcheck_status_completed_or_not(lead, step)メソッドをもっとシンプルに出来るかもしれません。

2020-10-24 12:30 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +        flash[:danger] = "#{flash[:danger]}未完了のタスクがあるため、#{step.name}を完了にできません。" if step.status?("completed")
ご指摘ありがとうございます。inactiveのときに不適切なflashメッセージが表示されてしまうということですね。

そうしたら、そもそも、step.statusがinactiveのときに、このメソッドを適用する必要があるかというと、ないかもしれません。inactiveの際は飛ばすように改修しましょうか。色々とリファクタリングの余地が出てきましたね。

2020-10-24 13:03 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +        flash[:danger] = "#{flash[:danger]}未完了のタスクがあるため、#{step.name}を完了にできません。" if step.status?("completed")
check_status_completed_or_notメソッドに一文を加えるだけで整合性は取れていますのでリファクタリングまではする必要はないと思いますが。

2020-10-24 13:07 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
> +      step.completed_tasks_rate = 100 if step.status?("completed")
この一文を入れると直接編集で完了を選んだ時、完了済み進捗編集時イベントが起動されて、「未」のタスクをすべて完了にするを選んだ後、進捗完了時イベントで進捗を完了にできるので、「未」タスクが残ったまま進捗が完了になることはないですよ。

2020-10-24 13:17 UTC, ruffini47 commented on app/controllers/leads/application_controller.rb
>        end
例えば、進捗１が保留のときsteps#showの画面の編集から「再開」を選んだ時、
新しいタスクは生成しないでよいのですが、params[:new_task].present?の記述が無ければset.tasks.not_yet.blank?ならば新しいタスクを生成してしまいます。結論から言えば、でもそれは進捗が保留のときでも「未」の進捗が無くても良い場合で、進捗が保留でも「未」のタスクが１つ以上ある状態を正にするならばparams[:new_task].present?は保留中の進捗を再開するときのみ使っているので要らないかもしれません。これは鈴木（文）さんの下のコメント「134行目が、157行目と表現が異なるのはなぜですか？
step.statusが"not_yet"や"inactive"の場合でも、タスクを新しくつくる必要があるでしょうか？？」にも関係しています。
私の意見としましては"not_yet"の場合は新しいタスクは必要ないですが、"inactive"のときは新しいタスクを作る方針のほうが一貫しているように思います。（このプルリクをあげたアプリを操作していてそう思いました。）

2020-10-24 13:20 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +        if !step.status?("completed") && step.tasks.not_yet.blank?
step.statusが"not_yet"のときは確かに新しいタスクは不要だと思いますが、"inactive"のときはむしろ新しいタスクを作るほうが一貫していると、このプルリクを含んだアプリを操作していて思いました。

2020-10-24 14:12 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +          Task.create!(step_id: step.id ,name: "new_task", status: "not_yet", scheduled_complete_date: params[:step][:scheduled_complete_date])
似たようなTask.create!ですが、よく見ると一つ一つ微妙に違った部分がありますので、メソッド化は見送りたいと思いますが、どうでしょうか？

2020-10-24 14:31 UTC, taniryuu approved these changes
ありがとうございます！
良い感じですね
私としては大丈夫かと思います。

2020-10-24 14:31 UTC, taniryuu commented on app/views/leads/tasks/edit_change_status_or_complete_task.html.erb
> +<h3><%= step_name(@step) %>:</h3>
良いですね！だいぶスッキリしてます👍

2020-10-25 03:23 UTC, ruffini47 commented on app/controllers/leads/steps_controller.rb
> +        check_status_and_redirect_to(@step, @step)
この分岐に行くのは、ユーザーが新規進捗を進捗ステータス：完了で生成する場合です。完了済の進捗を生成するので、そのままでは、「未」のタスク無し、「完了」のタスク無しで、進捗新規作成時イベントが働いてしまうので、「完了」タスクを生成させて、進捗完了時作成イベントを発生させるために「完了」タスクを生成しました。進捗ステータス「完了」で新規進捗を生成するときは、エラーメッセージを表示させて、進捗完了時イベントに飛ばすように変更しました。

2020-10-25 04:43 UTC, ruffini47 commented
谷口さん、鈴木（文）さんのコメントを確認、対応し変更点をプッシュしました。
ご確認よろしくお願いします。

2020-10-25 13:13 UTC, fumihisasuzuki approved these changes
自分でも動かしてきちんと検証してみないとわからなそうですね。現状成立しているようですので、私からはOKです！

2020-10-25 13:13 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +          Task.create!(step_id: step.id ,name: "new_task", status: "not_yet", scheduled_complete_date: params[:step][:scheduled_complete_date])
難しそうなら、あるいはDRYにならなそうなら、わざわざする必要はないと思います、承知しました。

2020-10-25 13:13 UTC, fumihisasuzuki commented on app/controllers/leads/steps_controller.rb
> +        if !step.status?("completed") && step.tasks.not_yet.blank?
修正ありがとうございます。

2020-10-25 13:14 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +        flash[:danger] = "#{flash[:danger]}未完了のタスクがあるため、#{step.name}を完了にできません。" if step.status?("completed")
承知しました。再考します。

2020-10-25 13:15 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
> +      step.completed_tasks_rate = 100 if step.status?("completed")
なんか、もっとシンプルに可読性をあげられないかな、と考えていました。
現状これで問題なさそうなら、とりあえず大丈夫です。

2020-10-25 13:16 UTC, fumihisasuzuki commented on app/controllers/leads/application_controller.rb
>        end
承知しました、現状、それで良いかと思います。

2020-10-25 13:37 UTC, ruffini47 commented
確認しました。
app/controllers/leads/steps_controller.rb52-55については鈴木（文）さんと多少すりあわせが必要ですが
それは、次のプルリクの課題としたいと思います。
マージしたいと思います。

2020-10-25 13:41 UTC, merged