Feature/users fix
taniryuu/Rer_Pro pull request #99
Opened 2020-11-08 03:05 UTC by taniryuu

## やったこと
企業内ユーザーを使いまわせるようリファクタリング
## やらないこと
特になし
## できるようになること(ユーザ目線)
特になし
## できなくなること(ユーザ目線)
特になし
## 動作確認
ページを手動で確認しました。
## その他
特になし。
コードレビューお願いします。

2020-11-08 15:01 UTC, ruffini47 commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.select :superior_id, users_list(superior_users(@users, @user)), autocomplete: "superior_id" %>
今更ではありますが、app/views/devise/registrations/edit.html.erbは何のためのファイルですか？deviseを扱ったことがないので教えていただけますでしょうか？

2020-11-08 15:08 UTC, ruffini47 commented on app/views/leads/leads/index.html.erb
>                  <%= render "index_sort", mark: " ▼ ", sort: "user_id" %>
これも今更なのですが、mark: "▼"は何のためのマークですか？

2020-11-08 15:48 UTC, ruffini47 approved these changes

2020-11-08 15:49 UTC, ruffini47 commented
確認しました。
１件だけ質問させて頂きました。
よろしくお願い致します。

2020-11-08 23:55 UTC, taniryuu commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.select :superior_id, users_list(superior_users(@users, @user)), autocomplete: "superior_id" %>
ユーザーモデルの情報を更新するページです。
使用している理由ですが、パスワードを更新する際のロジックが複雑で難しいのでdeviseに丸投げしている形です。

- パスワード更新時、現在のパスワードと更新したいパスワード、確認のパスワードを照合して更新

- 管理者とログイン中の本人がパスワードを更新できる

- ログイン中の本人は情報を更新するのに自分のパスワードが必要だが管理者はユーザーに合わせたパスワードを入力せずとも更新できる。

こんな機能がありますので時間ある時に実際に管理者と一般ユーザーでログインして触ってみてください。

2020-11-09 14:06 UTC, fumihisasuzuki requested changes
加勢いただきありがとうございます。非常に助かります。
users_listが綺麗に使い回せたようで良かったです。

1点だけコメントしました。

2020-11-09 14:06 UTC, fumihisasuzuki commented on app/controllers/leads/leads_controller.rb
>      user_ids_all = User.where(company_id: current_user.company_id).pluck(:id)
`user_ids_all = User.where(company_id: current_user.company_id).pluck(:id)`
は、
`user_ids_all = @users.pluck(:id)`
と、リファクタリングできませんか？

2020-11-09 14:10 UTC, taniryuu commented on app/controllers/leads/leads_controller.rb
>      user_ids_all = User.where(company_id: current_user.company_id).pluck(:id)
試しました！
pluckがうまくできなかったんですよね。
時間掛けるわけにもいかず、一旦このままです。

2020-11-09 16:15 UTC, ruffini47 commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.select :superior_id, users_list(superior_users(@users, @user)), autocomplete: "superior_id" %>
ありがとうございます。
一度自分でdeviseを使ってみます。

2020-11-13 03:25 UTC, fumihisasuzuki commented on app/controllers/leads/leads_controller.rb
>      user_ids_all = User.where(company_id: current_user.company_id).pluck(:id)
承知しました。

2020-11-13 03:25 UTC, merged